### ISSUE TITLE
Add attribute "Position" to Pogues model

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#104]
Add attribute "Position" associated with the "Declaration".
This attribute can take three values:
AFTER_QUESTION_TEXT
BEFORE_QUESTION_TEXT
AFTER_RESPONSE
DETACHABLE

Do you agree with this naming ?

For your information, i can't assign an issue in Pogues-Model project.

**Comment by FranckCo** [comment]
Done with commit a7c0663ab2440a177da796a701a6c7909762f52c in Pogues-Model. Please assign issues to the correct repository.

**Comment by ThomasPO** [comment]
Done
