### ISSUE TITLE
Define syntax for rich labels

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#105]
Pogues enables to create rich labels made of formatted text (italic, bold, hyperlink and icon with contextual information), which can embed data coming from previous questions, with variations depending on checked conditions.

For now, all this information has to be represented as a string, and the foreseen representation is described below. This proposal has to be validated.

Defautl label:  Une question à propos d’Internet.
Condition 1 : ${AVEZVOUSINTERNET} = 'OUI'
Label 1 : Vous vous appelez ${PRENOM}. Vous avez Internet. Utilisez-vous Google ? C’est bien Google !
Condition 2 : ${AVEZVOUSINTERNET} = ’NON’
Label 2  : Vous n’avez pas Internet. Si vous survolez cette petit icône ☂️, qui est une icône standard qui ne peut pas être paramétrée (ça sera un parapluie pour toutes les questions du questionnaire où on a choisi de mettre un icône), vous verrez apparaître de l’information.

—>
```markdown
{Une question à propos d’Internet.},
{${AVEZVOUSINTERNET} = ‘OUI’ | Vous vous appelez ${PRENOM}. Vous avez *Internet*. Utilisez-vous [Google](http://google.fr) ? C’est bien **Google** !},
{${AVEZVOUSINTERNET} = ’NON’ | Vous n’avez pas *Internet*. Si vous survolez cette petit icône ![Le texte qui apparaît quand on survole l’icône](/parapluie.png), qui est une icône standard qui ne peut pas être paramétrée (ça sera un parapluie pour toutes les questions du questionnaire où on a choisi de mettre un icône), vous verrez apparaître de l’**information**.}
```

**Comment by ThomasPO** [comment]
We suggest you to use [Velocity Template Language](http://velocity.apache.org/engine/1.7/vtl-reference.html) (VTL).
The syntax is:
# [ { ] if [ } ] ( [condition] ) [output] [# [ { ] elseif [ } ] ( [condition] ) [output] ]* [# [ { ] else [ } ] [output] ] # [ { ] end [ } ] 

We can easily parse this syntax.

**Comment by ThomasPO** [comment]
VTL: Ok
