### ISSUE TITLE
Use structured data to represent rich labels when saving a questionnaire

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#106]
Think about using structured data to represent rich labels instead of a regular string as defined in #105 when we serialise a questionnaire for saving purpose.

**Comment by BoogalooJB** [comment]
This option can be considered independently of #107 since saving and publishing a questionnaire are two distinct operations.

**Comment by ThomasPO** [comment]
Ok. You can manage the "saving" proccess differently from the publishing process.
