### ISSUE TITLE
Define consistent handling of default values for input fields

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#112]
If we want a field to appear with no value by default (when we create an object, such as a datatype), we should probably use an empty string when we create the object. If use `undefined`, we'll have the following message when attempting to update it with a real value :

`ReactDOMInput.js:134 Warning: NumericDatatypeEditor is changing an uncontrolled input of type number to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components`

If we use `null`, we'll have the following message:
`ReactDOMInput.js:42 Warning: value prop on input should not be null. Consider using the empty string to clear the component or undefined for uncontrolled components.`

To avoid this, we should do some kind of type coercion between the reducer and the ui, `null` becomes `''`, but it might not be the easier way to deal with empty default values.

So we'll go with assigning an empty string to values that should appear empty in the ui by default. If we need to represent them with `null` when we serialise data, we will do it during the serialisation phase (when we convert from state to model).

**Comment by ThomasPO** [comment]
and swith to `null` when you serialize ?

**Comment by BoogalooJB** [comment]
My comment was about a general rule to deal with empty values in the ui, and my point was : make things easy for the ui ('' for empty values), and if we need something else when we serialize, we will do it on a per item basis.

So about serializing : for strings that represent an id, `null` can be an option, but for strings that represent content (example: pattern string for a text datatype), we should stay with an empty string. Serializing numbers might be another situation to think of.

**Comment by ThomasPO** [comment]
I agree:
- for strings that represent an id, `null` is the option chosen
- for strings that represent content (example: pattern string for a text datatype), an empty string is the option chosen

**Comment by BoogalooJB** [comment]
And for numbers ? Legacy Pogues represented them when publishing as numbers, with `null` for the empty value. New Pogues use strings, with empty strings for empty values. Do we switch back to previous behaviour ?

**Comment by ThomasPO** [comment]
Yes, you can switch back to the previous behaviour.
Now, we can define strings in input fields of type "Numeric" (Minimum, Maximum, Decimals,...).
The previous behaviour seems better

**Comment by BoogalooJB** [comment]
> Now, we can define strings in input fields of type "Numeric" (Minimum, Maximum, Decimals,...).
The previous behaviour seems better.

Not what I was asking for. What allows the ui is one thing, how we serialize it an other.

**Comment by BoogalooJB** [comment]
Before closing this issue, check that numbers are serialized as numbers (not strings), with `null` if no value was filled in.

**Comment by ThomasPO** [comment]
Fixed. Issue closed
