### ISSUE TITLE
Question label and conditions

### ISSUE THREAD

**Issue by jbrudant** [InseeFr/Pogues#113]
When the label of a question depends on conditions, the label that appears when the component editor is folded is the label associated with the first condition. It might not be optimal, since this label can contain some references to other questions that would not be easily readable, and since it is related to a condition, it might not be significant without the context of the condition. And if we change the label associated with the first condition, this label will change too.

For now, the model cannot hold an extra information such as "brief description of the question, that does not depend on conditions".

Is this behaviour ok ? Or can we consider adding this extra element to the model ?

**Comment by BoogalooJB** [comment]
Suggestion : as a convention, we could consider that if the VTL string starts with an inline comment directive, this comment will be used as a default label ("the brief description" mentioned in my previous comment). It will enable us to use this label in the ui independently of the conditions, without needing to modify the model.

Remark : it does not question the behaviour which consists of filling in the label for the first condition with the label filled in the generic input when we add a condition. But if afterwards we update the label assigned to the first condition, it will not update the initial label.

**Comment by romaintailhurat** [comment]
Not sure if this particular issue is still relevant, but it might be linked to https://github.com/InseeFr/Pogues/issues/562.
