### ISSUE TITLE
Display error - response format

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#116]
- You create a questionnaire
- you create one sequence and two questions
- you add one simple response format for each question (not the same response format)
- you save
- you come back to the home page (don't forget to refresh the home page)
- you open your questionnaire previously created

you'll se that the two response formats are the same. The response format from the last question.

**Comment by HeidiKM** [comment]
In my questionnaire, the response format (after refreshing) is text (and not the format from the last question)

**Comment by ThomasPO** [comment]
That's the last format created in the questionnaire for a simple format

**Comment by HeidiKM** [comment]
ok, right, i delete my previous comm (certainly different effect while changing the format, instead of creating a new question)

**Comment by BoogalooJB** [comment]
Sorry, I don't understant. I created TT questionnaire following the process you described, and it seems to work for me.

**Comment by ThomasPO** [comment]
refresh (ctrl + F5) the home page ;)

**Comment by ThomasPO** [comment]
Fixed
