### ISSUE TITLE
Naming in serialized json (2)

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#119]
Replace `value` with `Value` (for a code value)
Replace `format` with `Format`
Replace `decimals` with `Decimals`
Replace `totalLabel` with `TotalLabel`

**Comment by BoogalooJB** [comment]
I think `totalLabel` was already serialized as `TotalLabel`, wasn't it ?

**Comment by ThomasPO** [comment]
Exactly. TotalLabel is well-serilized

**Comment by ThomasPO** [comment]
Fixed. Issue closed
