### ISSUE TITLE
Syncrhonisation issue in Gulp with babel and browserify

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#12]
I tried to remove es6 compiled files from tracked files, but gulp build fails when I run build after deleting src/js/models/*.js files. If I run gulp build:es6transpile and then gulp build again, it works.
I tried to ensure that babel was done before running browserify, using runSequence, but I didn't managed to make it work. Without any change, the build process seems to work, but I guess sometimes we can miss some changes made to the models since the last compilation.

Here's a way of doing it in a different way : https://github.com/BrowserSync/recipes/tree/master/recipes/gulp.browserify

**Comment by FranckCo** [comment]
Probably fixed, will be reopened otherwise.
