### ISSUE TITLE
Attribute GenericName

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#120]
The attribute `genericName` is not initialized. The defaultValue is `TODO:GENERIC_NAMES[0]`
It can be equal to "MODULE" or "SUBMODULE" (instead of "PARAGRAPH" before)

**Comment by ThomasPO** [comment]
In fact, it's only initialized for `Questionnaire` but not for `Sequence`

**Comment by ThomasPO** [comment]
Or maybe replace the `genericName` `Questionnaire` with `QUESTIONNAIRE`

**Comment by BoogalooJB** [comment]
Recap: we have to fill in the generic name for each sequence ? With:
- genericName for the questionnaire : QUESTIONNAIRE ;
- genericName for a sequence : MODULE ;
- genericName for a subsequence : SUBMODULE.

Is that it ?

**Comment by ThomasPO** [comment]
Exactly

**Comment by ThomasPO** [comment]
Fixed. Issue closed
