### ISSUE TITLE
ComponentGroup and page breaks

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#122]
We will use `ComponentGroup`s to store page breaks information. I think the idea is to create one `ComponentGroup` per page, isn'it ?

Because another option would be to have only one `ComponentGroup` for all the page breaks: this will group all the components that have an page break after them.

So which one:
1. one `ComponentGroup` per page ;
2. one `ComponentGroup` for all the page breaks ?

**Comment by ThomasPO** [comment]
First option: one `ComponentGroup` per page

**Comment by ThomasPO** [comment]
I deleted my previous comment.
How can you make only one `ComponentGroup`?

**Comment by BoogalooJB** [comment]
The component group will hold the references to the components followed by a page break. In fact that is the real information: which component is on a given page is a consequence of the structure of the questionnaire and where the page breaks stay.

**Comment by ThomasPO** [comment]
At the beginning, we thought about the first option but the second option seems to be sufficient to generate the web questionnaire.
Is that an option requires more work?

**Comment by BoogalooJB** [comment]
No, I developed the first one, but it is 5 minutes work to switch from one to another.

**Comment by ThomasPO** [comment]
Ok for the first option.
Issue closed
