### ISSUE TITLE
Error when loading old questionnaires

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#141]
When we load some old questionnaires that do not comply with the current questionnaire model we can encounter some errors. Depending on the kind of inconsistencies:
1. the questionnaire won't show up (endless spinner) ;
2. the questionnaire will be shown, but later when we try to edit to a component with inconsistencies, an error will occur.

In the second scenario, if we're not debugging at that time (ie we don't see the error in the console), the error can be unnoticed. But consequently, the app will be broken and some actions might not work, and this can be very confusing. For instance: an unnoticed error occurred with an old questionnaire, we go back to the questionnaire list and we choose a working questionnaire, and this questionnaire won't load (endless spinner) or the questionnaire will be loaded, but clicks will have no effect.

**Comment by BoogalooJB** [comment]
This happened when we update the response format parser to work with the `questionType` attribute (instead of guessing the question type based on the responses and the response structure). Some old questionnaires that do not have the `questionType` property will break the application.

**Comment by ThomasPO** [comment]
Dropped because of redesign
