### ISSUE TITLE
Improve build process for dev to automatically copy assets to dist folder

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#144]
For now, we need to run `npm run build` every time we update `index.html` (or any other asset) to copy the file in the `dist` folder (it includes the first time we try to run the application with `npm run dev`). A possible solution could be to use `webpack` `file-loader` to import these files (for example with `index.html`, we could do `import 'file?name=[name].[ext]!../index.html'` from the main javascript file). Another option could be to create a gulp task for dev which would track these assets and copy them when needed.

**Comment by ThomasPO** [comment]
Done even more

**Comment by ThomasPO** [comment]
Done even more
