### ISSUE TITLE
Add documentation about transformations between json and xml

### ISSUE THREAD

**Issue by BoogalooJB** [InseeFr/Pogues#147]
See TODO in https://github.com/InseeFr/Pogues/blob/38cb8ea2221cc6d1a6561112d9cf32288993f7d5/doc/remote-apis/questionnaire-json.md

**Comment by ThomasPO** [comment]
Moved to the Pogues Model repository

**Comment by ThomasPO** [comment]
Moved to the Pogues Model repository
