### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Pogues#16]
Associated to the search box in the general menu.

**Comment by BoogalooJB** [comment]
First attempt at implementing search. For now, it doesn't work : when the Quesitonnaire component renders itself to update after a search, the whole app is re-rendering.

I chose to offer the same filter functionnality (and the same menu) for the questionnaire-list component and the questionnaire component. If it's ok for everybody, we should rethink the questionnaire-list component : replacing the listbox by a simple list of questionnaires.

**Comment by BoogalooJB** [comment]
Filtering still not working, but part of the issus has been solved with commit 636c966b5a4abc5e02856517c4d1a2e8b7c2c917

**Comment by FranckCo** [comment]
Done
