### ISSUE TITLE
Define color guide

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Pogues#17]
See http://purple.herokuapp.com/, https://www.firebase.com/docs/styleguide.html, http://primercss.io/, or more generally http://www.thoughtworks.com/radar/techniques/living-css-style-guides

**Comment by FranckCo** [comment]
We need colors for:
- questions
- sequences (with diffent shades according to depth)
- menu
- questionnaire outlook background

**Comment by romaintailhurat** [comment]
Completed with https://github.com/InseeFr/Pogues/commit/2a31d54d157554644415977fb9b7f48dad7010d4
