### ISSUE TITLE
Specify how we configure the application

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Pogues#21]
Do we just load a JSON file? are there some standard ways of doing this?

**Comment by romaintailhurat** [comment]
That seems a perfect way to handler configuration : http://beletsky.net/2015/01/configuring-front-end-applications.html

I'll implement it tomorrow.

**Comment by romaintailhurat** [comment]
Config init with https://github.com/InseeFr/Pogues/commit/7168058d06c6438ba3ce6a88c3876f12ed3a1d1f
