### ISSUE TITLE
First level questions are store in the questionnaire at the same level that sequence owner

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#41]
The culprit seems to be the way we use the `appendComponent` in the QuestionnaireStore : we always append sequences and questions to the questionnaire itself, where we should append the questions to the sequence their belong to.

**Comment by BulotF** [comment]
Perhaps there is no bug. 
There is a way to choose the depth of the new element (but I don't understand why I cannot choose more than 2)
There is a symbol at the left of the name of the future Sequence or Question with a number (1 at first ; may be transformed into 2 if checked) : this is the depth.
If the number is 1, the new element is directly into the questionnary. If 2, it is into a module...

**Comment by romaintailhurat** [comment]
Fixed with https://github.com/InseeFr/Pogues/commit/e72c2497116824dcbde861b0618c423fedc4d334
