### ISSUE TITLE
No declaration in the generated questionnaire

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#48]
I created declaration(s) in "'Pogues", but no declaration appears in the generated questionnaire

**Comment by BulotF** [comment]
In the XML file from the survey : "TESTDUPO", the Child\Declaration are present, but empty.

**Comment by romaintailhurat** [comment]
Same problem as previously with declarations serialisation, it is "Text" and not "text"... Fixed in https://github.com/InseeFr/Pogues/commit/1c7dc053d9bd8fdc9338ab0a12d516655ca7ec64

**Comment by ThomasPO** [comment]
Validated.
We will improve the display in the generated questionnaire later.
Issue cloded
