### ISSUE TITLE
Display the current version and git reference

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#490]
Hi there!

It would be interesting to have the application current version and / or git or GitHub reference (i'm thinking [tags](https://github.com/InseeFr/Pogues/tags) here) somewhere in the deployed application (header or footer).

**Comment by romaintailhurat** [comment]
What about that [kind of solution](https://stackoverflow.com/a/46679785) using Webpack ?

**Comment by NicoLaval** [comment]
CRA will replace Webpack custom config soon (branch dev-cra is pretty ready to be merged into master).

A simple way to display is to import directly from package.json into the dedicated component:

```javascript
import { version } from '../*/package.json';
```

**Comment by romaintailhurat** [comment]
Nice, i'll wait for this version, and maybe i'll propose a PR. 😄 

Any timing for the merge ?

**Comment by romaintailhurat** [comment]
Back-end version can be part of this too (via a specific API call)

**Comment by romaintailhurat** [comment]
This can be displayed in the header:

![image](https://github.com/InseeFr/Pogues/assets/1663283/8092cf24-45c2-42f2-9431-fe2adb0deba5)

**Comment by romaintailhurat** [comment]
⬆️ A simple enhancement: add a link to the version tag directing to the release note (for example: https://github.com/InseeFr/Pogues/releases/tag/1.5.4)
