### ISSUE TITLE
Display a list of codes in the generated questionnaire

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#50]
The list of codes doesn't exist in the generated questionnaire. Perhaps a similar problem than issue #47 ?

**Comment by romaintailhurat** [comment]
For the record, CodeListReference are save, but not the CodeList(s).

**Comment by romaintailhurat** [comment]
After chit-chatting with https://github.com/FranckCo, we came to the conclusion that a refactoring of this features was necessary, we want to separate the code operations (create, update, delete) from the linking of questionnaire and code list.

For that, we propose :
1. the creation of a CodeListStore, that will hold the created code list and listen to every actions relating to their management.
2. the creation of specific actions :
  a. the CRUD on the CodeListStore
  b. the action that links a CodeList to a Question, i.e. modify the CodeLists object in the Questionnaire.

**Comment by romaintailhurat** [comment]
A specific branch exists now for this refactoring : https://github.com/InseeFr/Pogues/tree/code-list-management

**Comment by ThomasPO** [comment]
Validated.
Issue closed.
