### ISSUE TITLE
Default unit choice when logged in

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#505]
In the next-to-be-released version of Pogues, we introduce a list of units for the designer to choose.

Unfortunately, this choice currently *must* be done by the user, where probably they would like the previous behaviour, that is having this choice be made by default.

So, i propose we display by default the list of questionnaire of the default unit (the user's base unit).

**Comment by romaintailhurat** [comment]
Nicely done!

**Comment by loichenninger** [comment]
#575
