### ISSUE TITLE
Include a VTL editor

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#508]
[VTL](https://sdmx.org/?page_id=5096) is now one of the options for describing behaviours in general and controls in particular when using Pogues.

It is a complex language for which a proper code editor is needed.

We want at least:
- syntax highlighting
- syntax error catching

For that, we plan to integrate [Eurostat VTL editor](https://github.com/eurostat/vtl-editor).

**EPIC**:
- [ ] #510

**Comment by loichenninger** [comment]
### Problems remaining after integration

The editor doesn't underline in red syntax errors and the tooltip explaining the error doesn't pop up.

### How to reproduce the error

The branch containing the VTL editor integration is  [dev-cra-VTL-editor-rebase](https://github.com/InseeFr/Pogues/tree/dev-cra-VTL-editor-rebase).

**Comment by romaintailhurat** [comment]
Various experts are working on the matter.

**Comment by romaintailhurat** [comment]
No direct solution now, the problem is linked to the packaging of the editor. One solution would be to add the code directly. Analysis to come by @loichenninger , we'll choose a solution during this sprint.

**Comment by romaintailhurat** [comment]
#510

**Comment by romaintailhurat** [comment]
Epics are now managed at https://github.com/InseeFr/Umbrella
