### ISSUE TITLE
Add "Warning" in "DeclarationTypeEnum"

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#51]
Proposal to add value "Warning" in the enumaration  "DeclarationTypeEnum"

**Comment by FranckCo** [comment]
Done in commit d85e3cc5675d0e9515c8285c8794893970d8d28c.
Assigning back to PO to validate and close issue.

**Comment by BulotF** [comment]
Cannot publish any Questionnary. The last published one was on friday the 17th.
I can save it, but there is no attribute in the declaration (type or disjoinable) and there has never been...

**Comment by ThomasPO** [comment]
Issue closed...and i open a new issue : cannot publish any questionnaire
