### ISSUE TITLE
Unit tests fail when VTL editor is present

### ISSUE THREAD

**Issue by loichenninger** [InseeFr/Pogues#510]
We integrated the VTL editor from @eurostat/vtl-editor in the application.

### Current behavior

The unit tests of components integrating the editor fail. The error is  :

```
Automatic publicPath is not supported in this browser

      1 | /* eslint-disable no-console */
      2 | import React, { useState } from 'react';
    > 3 | import { AntlrEditor } from '@eurostat/vtl-editor';
```

### Reproduce

Launch yarn test on dev-cra-VTL-editor-rebase branch.

**Comment by romaintailhurat** [comment]
According to @NicoLaval it's linked to another issue we have with the VTL editor not properly displaying errors.
