### ISSUE TITLE
Mandatory choices during questionnaire creation

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#520]
When creating a questionnaire, the user can choose between XPath or VTL as the control language. 

This choice is not mandatory but **it should be**.

For historic reason, i propose that XPath stay the default choice.

**Comment by romaintailhurat** [comment]
More than just language choice, we want to make those choices mandatory:
- data collection mode selection
- language choice
- flow control type choice

**Comment by loichenninger** [comment]
This change is integrated in PR https://github.com/InseeFr/Pogues/pull/584

**Comment by romaintailhurat** [comment]
Working perfectly. 👌
