### ISSUE TITLE
Display a spinner when waiting for a questionnaire generation

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#526]
When clicking on the "Visualize" button, and thus waiting for the generation to be completed, it would be great to have a spinner in order to understand that something is happening.

I suggest to add a spinner-in-a-button, as you can see [in this example](https://dev.to/dcodeyt/create-a-button-with-a-loading-spinner-in-html-css-1c0h).

**Comment by romaintailhurat** [comment]
Validated in the validation env! Good job!

**Comment by loichenninger** [comment]
Linked to pull request #576
