### ISSUE TITLE
Define a policy for imports between modules

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Pogues#53]
We use imports (ES6) in most cases of imports between Pogues modules, and require (CommonJS) when importing external components (React, etc.).
We should have an explicit policy on using one or the other.

**Comment by romaintailhurat** [comment]
For documentation purpose :
www.2ality.com/2015/07/es6-module-exports.html
https://leanpub.com/exploring-es6/read#ch_modules

**Comment by ThomasPO** [comment]
Done
