### ISSUE TITLE
Merging two duplicated questionnaires doesn't work if sequences are renamed

### ISSUE THREAD

**Issue by loichenninger** [InseeFr/Pogues#533]
The merging functionality doesn't work in this particular case :
 - a sequence in questionnaire 1 have the same identifier that a sequence in questionnaire 2
 - the two sequences doesn't have the same name

This will happen especially when a new part of a questionnaire is created from the original : duplicate the questionnaire, then clean up and rename of sequences.

**Comment by romaintailhurat** [comment]
After various tests, it seems that we need to handle similar identifier for every object when merging in order to manage a partial or total duplication of a questionnaire.

Another way to manage the whole issue could be to generate new identifiers for every object when copying a questionnaire.

**Comment by romaintailhurat** [comment]
A 1st fix provided, nearly validated: only the Loop objects seem to not be handled.

The reference merged questionnaire is here: http://qfrmspogfolht01.ad.insee.intra/questionnaire/kyemupz5 (🔒 internal link, sorry).

A last validation should be made with filters.
