### ISSUE TITLE
Real statistical operations or series

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#542]
A Pogues questionnaire is tagged with the corresponding statistical operations or series, but those informations are currently only mocked ones. We need to connect to the dedicated API for an updated list (it's [Bauhaus ](https://github.com/InseeFr/Bauhaus)at Insee).

**Comment by romaintailhurat** [comment]
When parent processes metadata is missing: https://github.com/InseeFr/Pogues/issues/552

**Comment by loichenninger** [comment]
In link with https://github.com/InseeFr/Pogues-Back-Office/pull/132

**Comment by romaintailhurat** [comment]
Nice job!

It's the 3rd option of #522 that's implemented.

**Comment by romaintailhurat** [comment]
This feature will be roll out in production as soon as the Magma API is available.
