### ISSUE TITLE
Delete the serialisation functions in the Model classes

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#55]
The serialisation function is complete (see https://github.com/InseeFr/Pogues/commit/a5bd49675af48da86428d1a513c3410cea1985bd), the first attemps at it inside eache model classes must be cleaned up (see for example https://github.com/InseeFr/Pogues/blob/master/src/js/models/questionnaire.js#L38)

**Comment by ThomasPO** [comment]
Cancelled due to Redux migration
