### ISSUE TITLE
Questionnaire composition - UI concept

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#561]
Here is a first and very simple concept of the UI part of questionnaires composition:

![image](https://user-images.githubusercontent.com/1663283/153899986-e53cc3b1-a278-41c9-ba8c-8cde0849cf08.png)

The main idea here is to provide another kind of structural element for the questionnaire : a link to another questionnaire.

The element itself could be name after the target questionnaire. Editing this element display a UI where the designer can specify if its the whole questionnaire or a part of it that is integrated.

**Comment by romaintailhurat** [comment]
Need to provide sequence of UI steps to add a reference → @romaintailhurat

**Comment by romaintailhurat** [comment]
‼️ WIP @romaintailhurat 

# Adding a element - button placement
![image](https://user-images.githubusercontent.com/1663283/165080910-3dde123e-b011-44dd-8626-9dac305500fb.png)

# Adding an element - choice
![image](https://user-images.githubusercontent.com/1663283/165082030-d07c54c7-3372-48e2-97fd-36ed0cb4a559.png)

**Comment by romaintailhurat** [comment]
Progress have been made; currently a difficult part, handling the drag and drop algorithm for a reference object

**Comment by romaintailhurat** [comment]
# First experience with composition UI

## Global comments

- the external elements choice panel should be closer to the button (see what we have for the visualisation feature)

## 1 - Adding a ref to an empty questionnaire

It works, but we still have a warning message (see below) whereas we should not (the ref is indeed adding at least a sequence and a question).

![image](https://user-images.githubusercontent.com/1663283/174242219-2b1b8594-cba2-4614-829b-a539ae5593be.png)

**Comment by loichenninger** [comment]
The warning message for a questionnaire too short does not appear anymore on the screen if the questionnaire is composed of only an external reference.

**Comment by romaintailhurat** [comment]
@loichenninger __TODO__ Provide a cost estimation of implementing sequence integration (from a catalog questionnaire)

**Comment by loichenninger** [comment]
What is the behaviour wanted if a questionnaire contains a reference that does not exist anymore?

**Comment by romaintailhurat** [comment]
> @romaintailhurat What is the behaviour wanted if a questionnaire contains a reference that does not exist anymore?

Spec updated 😄

**Comment by romaintailhurat** [comment]
UI for a non-existing ref:

![image](https://user-images.githubusercontent.com/1663283/181771624-e91e47e8-11cc-4572-804a-60264b4f6d85.png)

Color is `#dadadb`

**Comment by romaintailhurat** [comment]
In order to be compliant with the spec (see above):

- the option list for adding an external element should be at the same distance from the button than the generation target list from the "Visualize" button
- we also need to delete the "+ Questionnaire" button in favor of a 3rd external element.

Note: here are the missing translations for the external elements ⬇️ 

- TCM reference
- Questionnaire reference
- Questionnaire merging

**Comment by romaintailhurat** [comment]
> In order to be compliant with the spec (see above):
> 
>  * the option list for adding an external element should be at the same distance from the button than the generation target list from the "Visualize" button
> 
>  * we also need to delete the "+ Questionnaire" button in favor of a 3rd external element.

Thank you @BulotF, those two issues are fixed!

**Comment by romaintailhurat** [comment]
Done
