### ISSUE TITLE
Tables total row

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#563]
A very common feature request: to be able to add a total row in tables. This total could simply be the display of a computed variable.

A simple UI for implementing that: add a `Total` field for the measured variable that refers to a computed variable.

![image](https://user-images.githubusercontent.com/1663283/154495258-4d72070a-bb84-4636-a002-97b47da4b179.png)

**Comment by AnneHuSKa** [comment]
ok in Lunatic 3
