### ISSUE TITLE
Pogues server responses should be JSON not XML

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#57]
Currently, when publishing a questionnaire, we get :

```xml
<ID>fr.insee-POPO-QPO-V1
<DEBUG>http://s90datalift.ad.insee.intra:8780/coltorb/fr/popo/v1/new?unite-enquete=123456789</DEBUG>
<DEBUG2>plop</DEBUG2>
</ID>
```

**Comment by lomobob** [comment]
Problem solved.

**Comment by ThomasPO** [comment]
Done.
Response header only with the location: http://s90datalift.ad.insee.intra:8780/coltorb/fr/popo/testresserv/new?unite-enquete=123456789
