### ISSUE TITLE
Mutation of the props object will be impossible in future React versions

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#58]
Starting at v0.14, the [props object will be frozen](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#breaking-changes).

A lot of state is not only distributed from parent component to children, but state is also mutated this way ! See for example : https://github.com/InseeFr/Pogues/blob/master/src/js/components/go-to.js#L56

That issue should be addressed in a future refactoring.

**Comment by romaintailhurat** [comment]
One possible first step in this refactoring will be the [component-editor](https://github.com/InseeFr/Pogues/blob/c4f9482add8a3eac57c0f12ecaed4d7525d48c83/src/js/components/component-editor.js) with the following strategy :
1. Pass the component to be edited through props (DONE)
2. Copy this props to the React component state
3. pass the delete / update functions to children component (eg GoTo, Controls)
4. this functions are called by the children and only modify the component editor state
5. the save function push the modified component through an action call
6. the questionnaire store replace the old component by the new one.

**Comment by ThomasPO** [comment]
Cancelled due to Redux migration
