### ISSUE TITLE
Add some measurement units

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#583]
🇬🇧 The list is:
- year
- person
- room
- kg
- cm
- cigarette
- brother or sister
- times

:fr: La liste est:
- ans,
- personnes,
- pièces,
- kg,
- cm,
- cigarettes,
- frères(s)/soeurs(s), 
- fois

‼️ Need to check that we want to support every kind of unit or not.

**Comment by romaintailhurat** [comment]
Update:
- ans: already handled by "années"
- personnes: to be added
- pièces: ???
- kg: to be added
- cm: to be added
- cigarettes: ???
- frères(s)/soeurs(s): ???
- fois: ???

??? marked entries to be discussed with @AnneHuSKa

**Comment by AnneHuSKa** [comment]
A measurement unit should be described if the answer without the unit is meaningless.
For instance :
"How many cakes did you eat last week ?" : no need to know the unit to answer
"How tall are you ?" you can answer in centimeters or meters, so you need a unit.

In the case above : 

    ans: already handled by "années"
    personnes: not really
    pièces: not
    kg: to be added
    cm: to be added
    cigarettes: no 
    frères(s)/soeurs(s): no
    fois: no

But we can discuss.

**Comment by romaintailhurat** [comment]
Final PR for Eno: https://github.com/InseeFr/Eno/pull/500

**Comment by romaintailhurat** [comment]
"ans" seems better suited for display than "années", will be changed.
