### ISSUE TITLE
TCM, handle modification rights for L120

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#588]
In order to integrate the TCM ("Tronc commun des ménages", or _Shared household question bank_), we would like to limit its modification to a few persons, the members of the L120 unit.

Ref : https://hackmd.io/zBa9sPS6TOSB6VjdNUwd7A?both#TCM

**Comment by romaintailhurat** [comment]
An implementation could be to use the `final` attribute of the [Pogues model](https://github.com/InseeFr/Pogues-Model/blob/main/src/main/resources/xsd/Questionnaire.xsd#L42).

**Comment by romaintailhurat** [comment]
Seems to work, when trying to save a modified questionnaire under DG75-L120, i got:

![image](https://user-images.githubusercontent.com/1663283/174623632-f5cd6c39-7b02-4508-9148-f1d3baeb13c8.png)

@loichenninger Is this the expected behavior ? If so, what would be the cost to be more explicit in the modal window ?

**Comment by romaintailhurat** [comment]
Deletion seems to be possible though 🥲

**Comment by loichenninger** [comment]
I added a restriction on deletion too [Pogues-Back-Office](https://github.com/InseeFr/Pogues-Back-Office/pull/135)

**Comment by romaintailhurat** [comment]
Indeed, deletion is now bypassed when not part of the restricted group. 

The implementation would be nicer with an explicit message instead of a silent routing to the home page. 😉

**Comment by romaintailhurat** [comment]
And everything still working from an habilitated user. 👍
