### ISSUE TITLE
Computed & external variables are lost

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#594]
At least two users have lost **all** their questionnaire computed variables. It's a huge bug because there's no real backup for this once a questionnaire is saved.

Currently, we don't have a clear idea of the path to this bug, extensive research must be done:

- to reproduce the bug
- to identify the code part responsible for this

**Comment by romaintailhurat** [comment]
Too complicated (and time consuming) to find the buggy path in the application code. Next strategy is to alert the user (via a pop-up or warning message) that they lost all their computed variables. This message ask the user to send a mail to the product team in order to identifiy the previous actions (and so help with a diagnosis).

**Comment by romaintailhurat** [comment]
@romaintailhurat message to be displayed →

**Comment by romaintailhurat** [comment]
@BulotF @ORogel La solution d'alerte ne fonctionne visiblement pas, les nouvelles occurrences du bug ne l'ont jamais levées. Il faut que l'on rediscute de la stratégie d'élimination de ce bug :(

**Comment by romaintailhurat** [comment]
An interesting news: this problem existed six years ago and was corrected. Probably something broke this fix. François will follow this trail.

**Comment by BulotF** [comment]
🇫🇷 Il y a 6 ans, il y a eu un problème dans la gestion du store Redux pour les variables externes et calculées : 
Le fonctionnement attendu était de recopier le state et le surcharger avec les variables modifiées.
Au lieu de ça, le state était écrasé avec les variables calculées et modifiées fournies à l'étape update.

Ainsi lorsqu'on modifiait un composant, les variables externes et calculées étaient effacées.

La correction mise en place il y a 6 ans a consisté à prendre les variables calculées et externes du store et à les recopier lors de l'appel à la modification d'un élément.

Depuis, les variables externes et calculées sont récupérées et envoyées lors de l'appel à la modification d'un élément.

Sauf dans au moins un cas.

Le cas identifié nécessite au moins 3 boucles : 
La boucle 3 est liée à la boucle 2 (qui est donc une boucle principale)
La perte des variables externes et calculées peut arriver lorsque la boucle 2 devient liée à la boucle 1 (la boucle 3 devient alors liée à la boucle 1 au lieu de la 2)

Je n'ai pas réussi à identifier d'autre cas, mais je ne garantis pas qu'il n'en reste pas.

2 possibilités de correction : 
- modifier uniquement le cas rare identifié
- corriger le comportement de modification des composants vis à vis du store Redux. Il faut alors se méfier avec toutes les modifications, car le bout de code est également utilisé dans le cas des suppressions (et conserver le state ne permet pas d'en enlever des éléments) : opportunité de rendre le code nettement plus clair, mais risque extrêmement fort de régressions (la liste des cas à tester loin d'être négligeable)

🇬🇧 You can use a translator, as I would have to...

**Comment by romaintailhurat** [comment]
We go for the first solution: patching for this wrong behavior only.

**Comment by BulotF** [comment]
Situation source du bug finalement trouvée grâce à une conceptrice : le déplacement d'un élément de questionnaire (séquence ou question a priori) pour lequel il existe un filtre dont il est : 
- soit le premier élément
- soit le dernier élément
- mais pas l'unique élément

Autre cas trouvé (mais a priori innocent des cas remontés par les concepteurs) : 
- la boucle C est basée sur (basedOn) la boucle B
- On modifie la boucle B pour la baser sur la boucle A
