### ISSUE TITLE
Refactor logging

### ISSUE THREAD

**Issue by FranckCo** [InseeFr/Pogues#6]

**Comment by romaintailhurat** [comment]
The refactoring should provide first conditionnal logging (i.e. depending on logging level) and maybe in second a remote logging (i.e. sending log events to a remote server)

**Comment by romaintailhurat** [comment]
There is now a logging utility ; we should use it to log info, see the [dev doc](https://github.com/InseeFr/Pogues/wiki/Developer-documentation#logging).
