### ISSUE TITLE
Household members pairing UI component

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#601]
A new kind of question type will be provided: a [household members pairing](https://github.com/InseeFr/Umbrella/issues/2) component.

# Type of question

![image](https://user-images.githubusercontent.com/1663283/188407546-33e367d4-893d-4db2-b372-ba0ded37fca0.png)

🇫🇷 "Liens deux à deux"
🇬🇧 "Household members pairing"

# Configuration

![image](https://user-images.githubusercontent.com/1663283/194864703-4859abc7-0a04-4f65-a08d-fd2be0c40cea.png)

### Source variable

__Source variable__ is a questionnaire variable input with completion, indicating the variable (vector) holding the list of househould members.

🇫🇷 "Variable source"
🇬🇧 "Source variable"

### Loop

The link matrix is used to iterate over the links. To do so, the user will use the Loop feature of Pogues, with the "Based on" (:fr: "Basé sur") field selecting the matrix (by using the component name in Pogues). Filter can be applied using the "Excluding" (🇫🇷 "Sauf") field.

**Comment by romaintailhurat** [comment]
See also #600

**Comment by romaintailhurat** [comment]
Reviewed by @AnneHuSKa

**Comment by ORogel** [comment]
🇫🇷 
Paramétrages possibles (à terme) : 
- choix des deux axes (X et Y) -> dans un premier temps, uniquement un axe unique proposé au concepteur (X=Y)
- possibilité de filtrer ce qu'on veut pas comme croisement en utilisant les variable `xAxis` et `yAxis`(actuellement uniquement la diagonale) -> non proposé dans un premier temps au concepteur, mis en dur dans Pogues  et passage dans le DDI (modélisation ?) ?
- la liste des options -> dans un premier temps, non proposé en option au concepteur et mis en dur dans Pogues et passage dans le DDI (modélisation ?) ?
- libellé de la question : à proposer par défaut ? modification possible ou champ grisé dans la question ?

Référence (modélisation Lunatic) : https://github.com/InseeFr/Lunatic/blob/v2-develop/src/stories/pairwise/links/links.json

🇬🇧 
Possible settings (eventually) : 
- choice of two axes (X and Y) -> initially, only one axis proposed to the designer (X=Y)
- possibility to filter what we don't want as a crossover by using the variables `xAxis` and `yAxis` (currently only the diagonal) -> not proposed at first to the designer, hardened in Pogues and passed to the DDI (modeling ?) ?
- the list of options -> at first, not proposed as an option to the designer and hard-coded in Pogues and passed to the DDI (modeling?) ?
- wording of the question : to be proposed by default ? possible modification or grayed field in the question ?

Reference (Lunatic modelisation) : https://github.com/InseeFr/Lunatic/blob/v2-develop/src/stories/pairwise/links/links.json

**Comment by romaintailhurat** [comment]
Next alpha release for validation won't include the reciprocity matrix (a change is needed in Lunatic in order to have a full transfo in Eno).
