### ISSUE TITLE
Eno interviewer view API call

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#602]
Currently Eno API doesn't distinguish between CATI and CAPI mode, but it will soon be done.

Accordingly, Pogues must adapt and be able to call the API with the new values of the API endpoint.

Note: we will stick with one visualization option for interviewer view since there is no difference in Queen. In the future, we might provide two different options.

**Comment by ORogel** [comment]
Eno distingue désormais depuis la v2.3.10 (lib) et v1.5.0 (WS) les modes CAPI et CATI. Pour déployer la version en production, la visualisation "Poste Enquêteur" se fait désormais sur le mode "CAPI" (adaptation effectuée dans le Back de Pogues). Attention : si seul le mode CATI est sélectionné ou s'il existe des distinctions de saisie de déclarations et notamment certaines uniquement en "CATI", elle n'apparaitront pas à la visualisation. La double visualisation doit être donc implémentée sans trop attendre (exemple : TIC qui fait du T"l"phone en mars (recette à l'automne))

**Comment by romaintailhurat** [comment]
See #612
