### ISSUE TITLE
Generation target options update: new CATI target & new list

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#612]
CATI & CAPI modes are [now distinct in Eno](https://github.com/InseeFr/Pogues/issues/602). Pogues needs to be updated by adding a new generation target for CATI, in the same time slightly modifying the option list.

New list:

🇫🇷 

Web V1
Web V2
Enquêteur face-à-face
Enquêteur téléphone
Papier
Spécifications
Métadonnées

:gb:

Web V1
Web V2
Interviewer face-to-face
Interviewer phone
Paper
Specifications
Metadata

**Comment by romaintailhurat** [comment]
Implies the creation of a new endpoint in Pogues API

**Comment by BulotF** [comment]
https://github.com/InseeFr/Pogues/tree/devSplitQueenCapiCati
Waiting for somewhere to deploy

**Comment by romaintailhurat** [comment]
The list is validated (it is "Spécification" instead of "Spécification*s*" but in fact it makes sense. 😄 

Regarding the generation:

- Web V1 : OK
- Web V2 : The question label is not displayed
- Face to face : same
- Phone : same (see screenshot below)
- Paper : OK
- Spec : OK
- Metadata : OK

![image](https://user-images.githubusercontent.com/1663283/199753076-ca270496-6db6-432f-a16b-2024f9b6bca4.png)

**Comment by BulotF** [comment]
@ORogel : je confirme le diagnostic de Romain : Il doit y avoir une incohérence entre la version Eno et la version Lunatic pour web V2, Face à face et téléphone : les libellés de question ne s'affichent pas (OK pour web V1 et les autres formats de sortie)
Je ne sais pas si on attend un Label contenant une chaîne de caractères ou si on attend un Label au format objet contenant un attribut value avec cette même chaîne de caractères... Mais on a l'autre.

**Comment by romaintailhurat** [comment]
> @ORogel : je confirme le diagnostic de Romain : Il doit y avoir une incohérence entre la version Eno et la version Lunatic pour web V2, Face à face et téléphone : les libellés de question ne s'affichent pas (OK pour web V1 et les autres formats de sortie) Je ne sais pas si on attend un Label contenant une chaîne de caractères ou si on attend un Label au format objet contenant un attribut value avec cette même chaîne de caractères... Mais on a l'autre.

🇬🇧 Regarding disappearing labels, we know what is the cause: one or more trailing spaces or tabs in the VTL expression.
🇫🇷 La disparition des libellés est un problème d'espaces ou tabulations surnuméraires dans l'expression VTL

**Comment by romaintailhurat** [comment]
🇬🇧 Feature validated! 👌

**Comment by romaintailhurat** [comment]
Released with https://github.com/InseeFr/Bowie/releases/tag/1.0.0
