### ISSUE TITLE
Questionnaire composition - Import referenced questionnaires loops

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#616]
🇬🇧 As we import variables from a reference questionnaire into the host one, we would like to also import loops. A first crucial use case is the use of the inhabitants loop from the TCM mandatory sequence, used in other host questionnaire elements to iterate over.

🇫🇷 Lorsque l'on fait référence à un questionnaire dans Pogues, on souhaiterait importer aussi les boucles définies dans le questionnaire cible. Un exemple d'usage important est pour le module du TCM listant les membres des habitants, liste sur laquelle on voudrait ensuite pouvoir itérer.

**Comment by ORogel** [comment]
A priori du back-office

**Comment by BulotF** [comment]
Hypothèse : 
Les Components de type LOOP du questionnaire référencé sont bien récupérés, mais certains de leurs éléments ne sont pas rafraichis lorsque les objets qu'ils référencent changent d'identifiant. Principaux suspects : initialMember et finalMember (par contre, ceux des filtres le sont a priori) ; parent est aussi suspect, mais moins...

**Comment by romaintailhurat** [comment]
:gb: Loop from questionnaire are note available at the computed variable level

:fr: Il manque les boucles de référence au nvieau de la "Portée" d'une variable calculée
