### ISSUE TITLE
Questionnaire composition - TCM import list

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#617]
🇬🇧 We provide 3 options for external elements: TCM, other questionnaires and merging (see #561).

We would like the TCM list to be composed of TCM-only questionnaire. Several options:

- the view is the current view but already filter to DG75-L120 (DRTI stamp)
- the view is the current view but already filter to a _to-be created_ TCM stamp ⭐ 

The latter being the favorite, the goal here is to reduce the load for household questionnaire designer.

To be discussed. 🤗 

🇫🇷 Suite au développement de la composition de questionnaire, on propose trois options d'ajout d'éléments externes : références à des modules du TCM, références à d'autres questionnaires, fusion (voir #561)

Pour le TCM, on souhaiterait que la liste de questionnaires soit limitée aux seuls modules du TCM. Plusieurs options:

- on garde la vue actuelle mais pré-filtrée sur le timbre DG75-L120
- on propose une vue pré-filtrée sur un timbre à créer TCM ⭐ 

Cette dernière option est la meilleure en terme d'usage par les enquêtes ménages.

À discuter 🤗

**Comment by BulotF** [comment]
Proposition : en attendant d'avoir une méthode plus propre d'identifier les TCM (métadonnée RMéS ?), je vais mettre en place le filtre sur le timbre.
Côté position du questionnaire référencé, il me semblerait plus utile pour les utilisateurs de le mettre en première position du questionnaire hôte, alors qu'une référence classique serait positionnée à la fin...

**Comment by romaintailhurat** [comment]
OK, but in this case we create the TCM stamp no?

**Comment by romaintailhurat** [comment]
We will use a specific Campaign for tagging the TCM modules.

**Comment by romaintailhurat** [comment]
> We will use a specific Campaign for tagging the TCM modules.

We may reconsider this, as me may manage campaign information in another tool (AC⚡DC) in a few months

**Comment by romaintailhurat** [comment]
TCM questionnaires are "marked" using special metadata:

![image](https://user-images.githubusercontent.com/1663283/223765150-79844353-ee9b-4b94-913d-d6f42c5714ac.png)
