### ISSUE TITLE
Performance overhaul with large questionnaires

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#622]
Some surveys produce very large questionnaires*. In those cases:

- the UI gets very slow
- the questionnaire generation may takes several minutes to complete.

I think the 1st issue is more problematic than the 2nd (that will be took care with the Eno refactoring). A first analysis should be started in order to pinpoint bottlenecks and other performance issue - maybe with the help of some JS experts?

`*` internally, see some made by the ENL team, for example: `questionnaire/l7j0vaea`

**Comment by romaintailhurat** [comment]
@BulotF @MickaelMenet another input for Jonathan

**Comment by BulotF** [comment]
Lors de la mise à jour d'un composant, de nombreux autres composants qui ne dépendent pas de lui se re-rendent aussi.

L'ajout de useCallback (potentiellement signalés par Sonar) pourrait déjà beaucoup améliorer la situation, en attendant de creuser plus profondément.

**Comment by JulienCarmona** [comment]
@laurentC35 je relance
 input for Jonathan ?
