### ISSUE TITLE
Link to new Eno for Lunatic V2 questionnaire generation

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#623]

**Comment by ORogel** [comment]
dev into https://github.com/InseeFr/Pogues-Back-Office/tree/dev-stromae-v2-lunatic-v2
include : new CATI Queen visualize WS

**Comment by ORogel** [comment]
Eno deploy into kube for this version : https://production-eno-lunatic-v1.kube.developpement.insee.fr/swagger-ui/index.html

**Comment by romaintailhurat** [comment]
Released with https://github.com/InseeFr/Bowie/releases/tag/1.0.0
