### ISSUE TITLE
Reduce UI technical debt

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Pogues#629]
- convert React Class-Based Components to Functional Components (including the classes that don't extend Component but ControlWithSuggestion)
- solve Dependabot Critical alerts (5 of 21) ; 3 of them need react-scripts update
- reduce other alerts by upgrading dependencies or change dependencies
- sonar : solve bugs (2 of 5 are critical) and security hotspots (4 : all medium, including 1 in the uuid calculation)
- reduce code smells (151), including :
	- 33 critical, including 27 Cognitive Complexity
	- 30 code smells in 1 file : src/forms/controls/rich-textarea/lib/markdown-vtl-parser.js
- increase test coverage

**Comment by romaintailhurat** [comment]
@BulotF A good input to Jonathan's intervention ?

**Comment by JulienCarmona** [comment]
@laurentC35 Je relance le sujet
Est-ce que c'est un bon ticket pour Jonathan ?

**Comment by laurentC35** [comment]
On temporise un peu ce sujet là.

On va lui donner des travaux sur challenger les possibilités techniques pour répondre au besoin de l'articulation des questionnaires plus tôt.

Et ça pourrait résoudre le PB de performance côté UI sur les gros questionnaires.
