### ISSUE TITLE
Wrong handling of filter start or end element deletion

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#630]
🇬🇧 
When deleting a start or end element of a filter, the filter itself is not properly handle in the UI (need to check if the model is ok, see #605 )

For an example, see [this questionnaire](https://pogues.dev.insee.io/questionnaire/l9zpmbyy).
🇫🇷 
L'interface graphique ne gère pas correctement la suppression d'un élement au début ou à la fin d'un filtre (vérifier que ce soit également bien fait au niveau modèle, voir #605).

Pour exemple, voir [ce questionnaire](https://pogues.dev.insee.io/questionnaire/l9zpmbyy).

**Comment by BulotF** [comment]
La suppression : 
- du premier ou du dernier élément 
- d'un filtre ou d'une boucle
entraîne la suppression de ce dernier / cette dernière

**Comment by romaintailhurat** [comment]
Validated!
