### ISSUE TITLE
VTL label with trailing spaces or tabs are not displayed 

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#635]
🇬🇧 In VTL mode, a label with one or several trailing spaces or tabs after the last double quote will not be displayed. It could be handled in Pogues, or in Lunatic, or both.

🇫🇷 En mode VTL, un libellé  contenant un ou plusieurs espaces ou tabulations après le dernier double quote `"` ne sera pas affiché. Le problème peut être réglé au niveau Pogues ou Lunatic, ou les deux.

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Pogues/issues/688
