### ISSUE TITLE
Display the list of codes created

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#64]
After the following steps:
- i create and validate a new list of codes
- i save the questionnaire
- i quit Pogues application (or come back to the home page)
- i get back the questionnaire 

==> the list of codes created previously is not visible in the dropdown but i can see the list of codes in the generated questionnaire

**Comment by romaintailhurat** [comment]
Already identified the issue : our base method for identifying elements of a questionnaire is [a kind of hash of the Date function](https://github.com/InseeFr/Pogues/blob/master/src/js/models/component.js#L26).

Problem is, we want some components (maybe all of them one day) to be identified by a lasting `id` - that is the case for the code lists.

Proposed solution :

 - custom code lists are identify with a fixed id right now, for example with the [fixed pattern function used for questionnaire name](https://github.com/InseeFr/Pogues/blob/master/src/js/utils/name-utils.js#L14),
 - code list specifications should come with a unique id hold and managed by the metadata repository.

**Comment by romaintailhurat** [comment]
@FranckCo we should update the SPARQL query to retrieve the unique id, isn't it ?

**Comment by ThomasPO** [comment]
Issue for the code list from the metadata repository is [here] (https://github.com/InseeFr/Pogues/issues/78)

**Comment by ThomasPO** [comment]
Fixed
