### ISSUE TITLE
Action buttons on multiple lines elements

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#656]
The devs in the `dev-ref-loops` branch add several features including a reference to another questionnaire. This comes with a button to open the referenced questionnaire. But it comes with a not-so-pretty UI, compares current main:

![image](https://user-images.githubusercontent.com/1663283/218053987-06f5bfc3-c7c4-4b48-a0d0-d09593227b60.png)

with the branch:

![image](https://user-images.githubusercontent.com/1663283/218054084-046c8ac1-abc1-44de-8dcd-6d71b96196df.png)

Some CSS adaptation needed. 😅

**Comment by HavreLoic** [comment]
Hi @romaintailhurat can you assign it to me?

**Comment by romaintailhurat** [comment]
Hi @HavreLoic!

Sorry, this has already be done. 😄

**Comment by HavreLoic** [comment]
Ok thank you for letting me know.
