### ISSUE TITLE
Define a pattern for the date format

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#66]
Your opinion ?
Propose a list of patterns:
YYYY-MM-DD
YYYY-MM
YYYY
hh-mm (for hours and minutes)
etc.
or
ask the user for defining the pattern ?

**Comment by BulotF** [comment]
DD/MM/YYYY already done in Eno for two postponed surveys...

**Comment by romaintailhurat** [comment]
We could provide a way to configure the default pattern (for instance by using the config file), and then also provide a dropdown (starting with the default choice previously configured) with all patterns available for users to choose.

**Comment by romaintailhurat** [comment]
Existing feature.
