### ISSUE TITLE
Unifier le MemberReference de Iteration à 2 éléments systématiquement

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Pogues#667]
La liste memberReference contient soit 2 éléments : le premier et le dernier, soit un seul s'ils sont identiques.

Ceci nécessite de créer un traitement spécifique côté front et le même côté back, lorsqu'ils sont identiques.

Mettre systématiquement 2 éléments (même identiques) simplifie le code côté front, comme côté back (depuis la référence de questionnaire)
Cette simplification est sans effet côté Eno : il calcule des positions pour tous les éléments du questionnaire, puis va chercher la plus petite et la plus grande.

**Comment by romaintailhurat** [comment]
Pas de régression constatée.
