### ISSUE TITLE
Questionnaire composition - Loop in host questionnaire based on referenced loop not working

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#669]

**Comment by romaintailhurat** [comment]
To be worked on after a pass on Eno

**Comment by nsenave** [comment]
When importing a questionnaire ("external element") in the front app, loops of this questionnaire are also imported in the UI. 

The issue: if the used defined a "linked loop" in the host questionnaire, based on a loop which come from a referenced questionnaire, the back doesn't set this linked loop scope's correctly.

**Comment by nsenave** [comment]
Actually seems that the de-refrencing process make the linked loop disappear in the output, working on it.

**Comment by nsenave** [comment]
It was a dumb mistake: when there are loops in a referenced questionnaire, the method was setting a new list of loops in the host (removing its own loops). (The problem was more generic than a linked loop issue.)

https://github.com/InseeFr/Pogues-Back-Office/pull/160
