### ISSUE TITLE
Questionnaire composition - Deduplicate code lists with same business id

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#672]
We can have two (or several) lists with the same business id in host and ref. In this case, we need to deduplicate and keep only one such list: the first in rank in the global questionnaire.

**Comment by romaintailhurat** [comment]
Done

**Comment by nsenave** [comment]
Rephrasal with an example for the record:

- host questionnaire has a code list `FOO_CODE_LIST`
- a referenced questionnaire has also a code list named `FOO_CODE_LIST` (which may have a different content)

=> Composed questionnaire would have the `FOO_CODE_LIST` that is defined in the host (the one in the referenced questionnaire would be ignored)
