### ISSUE TITLE
Merge API : questionnaire//vars and questionnaire//variables

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Pogues#673]
/api/persistence/questionnaire/{id}/vars : Get the variables of a questionnaire (used by Public Enemy)
and 
/api/persistence/questionnaire/{id}/variables : Get the variables of a questionnaire, used for pogues frontend

can be merged : Replacing externalQuestionnaireVariables.Variable by externalQuestionnaireVariables in Pogues UI is enough to use the API useful to Public Enemy.

An evolution of the first one would be to get the variables from the "dereferenced" questionnaire, but : 
1) referenced questionnaires should not be host questionnaires too
2) If the become host too, their variables list should be the "dereferenced" questionnaire's one, as for Public Enemy.

**Comment by JulienCarmona** [comment]
@nsenave @BulotF @laurentC35 
On close ce ticket car sera jamais prio.

Mais vous pouvez clairement profiter d'un futur dev sur ces APIs pour refacto et faire de l'amélioration continue

**Comment by nsenave** [comment]
> @nsenave @BulotF @laurentC35 On close ce ticket car sera jamais prio.
> 
> Mais vous pouvez clairement profiter d'un futur dev sur ces APIs pour refacto et faire de l'amélioration continue

Oui si on se retrouve gêné par ça un jour on fera du refacto à ce moment-là.

**Comment by laurentC35** [comment]
Avec l'idée de créer un référentiel de variable (#refonteDePogues), on fera sautet certainement les deux implémentations qui existe
