### ISSUE TITLE
Add 3 variables to API persistence/questionnaires/search/meta

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Pogues#674]
First used for the "home" page and the "search" page, this API is also used for the choice list on merging and composing questionnaires.

For the last need, 3 new variables are needed : 
- Name : the business id, used for the questionnaire navigation
- flowLogic : needed to check if flows are the same :  https://github.com/InseeFr/Pogues/issues/664
- formulasLanguage : needed to check if formula languages are the same : https://github.com/InseeFr/Pogues/issues/665

**Comment by romaintailhurat** [comment]
Can we close this issue @BulotF ?
