### ISSUE TITLE
Roundabout component - Design in Pogues

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#678]
🇬🇧 Enable the Roundabout component in Pogues

🇫🇷 Permettre l'utilisation du composant Rond-point dans Pogues

**Comment by laurentC35** [comment]
In UX design, it's probably a single checkbox which indicates whether roundabout navigation is required inside Loop form.
The roundAbout is generated with Eno according to the new Props

![image](https://github.com/InseeFr/Pogues/assets/38245508/0d4d0f38-8f88-4bdb-9cd6-89b524c354ed)


⚠️ Keep a eye on ddi modeling

**Comment by romaintailhurat** [comment]
See https://github.com/InseeFr/Pogues/issues/649

**Comment by romaintailhurat** [comment]
Though the simplicitiy of the design in this [comment](https://github.com/InseeFr/Pogues/issues/678#issuecomment-1721249921) is enticing, it doesn't cover the possibility or need to specify completion indicator.

In the census questionnaire implementation of the Roundabout, each iteration has a completion status that is the result of a VTL formula.

A first version in Pogues may not provide this feature but it may be required in the future (for example if we want to integrate the census questionnaire back in Pogues).

**Comment by BulotF** [comment]
En fait, j'ai beaucoup de mal avec la présentation que je viens de proposer.

J'aurais préféré présenter le rond-point en utilisant l'esthétique des séquences.

- un label pour le rond-point
- un label pour l'occurrence
- la possibilité de 0 ou plusieurs Déclarations
- la possibilité de 1 ou plusieurs Boucles (liées entre elles) avec pour chacune : 
  - "Libellé de la boucle" (si plusieurs boucles)
  - "Indicateur d'occurrence terminée"
  - "Indicateur d'occurrence commencée"

On aurait ainsi une définition plus proche de celle du DDI.

Problème à mon sens : trop de boutons dans la barre du bas.
Ce problème pourrait être contourné en regroupant : Séquence ; sous-séquence et rond-point

**Comment by romaintailhurat** [comment]
Proposition d'affichage dans la vue structurelle.

__Non sélectionné 👇 __

![image](https://github.com/InseeFr/Pogues/assets/1663283/351c6d9a-5e3e-4018-acae-9fc8552887dd)

__Sélectionné 👇 __

![image](https://github.com/InseeFr/Pogues/assets/1663283/d4ade162-556f-4929-8a69-acf0732cc610)

**Comment by romaintailhurat** [comment]
> Problème à mon sens : trop de boutons dans la barre du bas. Ce problème pourrait être contourné en regroupant : Séquence ; sous-séquence et rond-point

@BulotF on peut juste supprimer le bouton _Publier_ qui n'a jamais servi

![image](https://github.com/InseeFr/Pogues/assets/1663283/0229d7c8-c41a-4760-897d-a28d9400f3a2)

**Comment by BulotF** [comment]
Complément : 
Le bouton rond-point n'est activé que lorsqu'on sélectionne une séquence, une sous-séquence ou une référence à un autre questionnaire.

Dans un premier temps, on ne proposera qu'une seule boucle, donc le rond-point ne référencera pas une boucle, mais la décrira.

Au niveau description de la boucle : 
- le premier élément sera initialisé avec l'élément sélectionné (le premier après le rond-point)
- les éléments qui composent la boucle seront d'ores et déjà connus, donc la boucle sera basée sur une autre (pas de min et de max)
- si l'élément "Sauf" est renseigné, un "Libellé des occurrences non concernées" est demandé

Au final : 
- Libellé
- 2 onglets : "Boucle" et "Déclarations" (contenu similaire à l'onglet Déclarations des séquences)

Dans l'onglet "Boucle" (évolution de la pop-up des boucles) : 
- Identifiant *
- Basé sur *
- Sauf
- Libellé des occurrences exclues (visible seulement si "Sauf" a du contenu)
- Début : initialisé avec l'élément sélectionné
- Fin *
- Libellé d'une occurrence *
- Indicateur personnalisé d'occurrence commencée
- Indicateur personnalisé d'occurrence terminée

**Comment by BulotF** [comment]
Changement de la modélisation dans Lunatic : 

1) Disparition des concepts suivants : 
- Indicateur personnalisé d'occurrence commencée
- Indicateur personnalisé d'occurrence terminée

2) Evolution du concept : 
Libellé des occurrences exclues (visible seulement si "Sauf" a du contenu)
Ca devient une description, complémentaire au label des occurrences, qui peut être affiché que l'occurrence réponde ou non.

3) Ajout de concepts : 
- locked : booléen : "Autoriser le répondant à revenir sur l'occurrence une fois complétée ?"
- une variable collectée "progressVariable" qui permet d'indiquer où le répondant s'est arrêté au niveau de l'occurrence (quelle page) ; de mon sens, il s'agit d'une paradonnée, car elle n'est pas collectée explicitement par le répondant. On pourrait envisager de la faire générer par Eno à partir du DDI avec un nom générique basé sur le nom du rond-point.

**Comment by AnneHuSKa** [comment]
@BulotF : je crois que la condition Sauf est à l'envers.
J'ai saisi : 
![image](https://github.com/InseeFr/Pogues/assets/71011059/b722470b-13d5-4bc8-98eb-02785c21cd0e)

et j'ai 
![image](https://github.com/InseeFr/Pogues/assets/71011059/20da2950-87fc-4698-8c57-43fa081fb2da)

**Comment by nsenave** [comment]
Peut-être des ajustements plus tard mais ok 👍
