### ISSUE TITLE
Questionnaire composition - Variables names check

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#681]
🇬🇧 In the case of a host questionnaire with at least a reference, we need to check the uniqueness of variables names.

Three cases:
1. when adding a ref, check if there are duplicates. If so, don't allow reference. 
2. when creating a new variable in the host questionnaire, check it doesn't collide with ref variables (using the existing variable name check)
3. when a new variable is added to the already added ref questionnaire and the name collides, we alert at the host level (as in 2.)

_TODO_ UX for the 1st case

🇫🇷 Dans le cas d'un questionnaire hôte avec au moins une référence, nous devons vérifier l'unicité des noms de variables.

Trois cas de figure :
1. lors de l'ajout d'une référence, vérifier s'il y a des doublons. Si c'est le cas, ne pas autoriser la référence. 
2. lors de la création d'une nouvelle variable dans le questionnaire hôte, vérifier qu'elle n'entre pas en collision avec des variables ref (en utilisant la vérification du nom de la variable existante)
3. lorsqu'une nouvelle variable est ajoutée au questionnaire ref déjà ajouté et que le nom entre en conflit, nous alertons au niveau de l'hôte (comme dans le point 2).

_TODO_ UX pour le 1er cas

**Comment by BulotF** [comment]
J'ai un problème avec le cas 3 : 
Il suppose que lorsque l'on souhaite modifier un questionnaire, on vérifie l'ensemble des questionnaires qui le référencent et, pour chacun d'entre eux, on vérifie s'il y a des doublons entre : 
- d'une part les variables du questionnaire référencé
- d'autre part les variables du questionnaire référençant et les variables des autres questionnaires référencés

S'il y a parmi les questionnaires référençant, un questionnaire qui a valeur de test, il pourrait bloquer une évolution légitime sur un questionnaire référence.

Je jugerais plus sain de tester dans les 2 cas précédents et à l'ouverture d'un questionnaire.
S'il y a doublon, j'aurais remplacé l'action derrière "Visualiser" pour faire apparaître la liste des doublons et ainsi faciliter leur nettoyage. Par contre, alors que j'aurais bloqué l'ajout d'une variable du questionnaire dont le nom existe déjà, j'aurais laissé faire l'import d'un questionnaire externe et sa sauvegarde.

**Comment by romaintailhurat** [comment]
> Il suppose que lorsque l'on souhaite modifier un questionnaire, on vérifie l'ensemble des questionnaires qui le référencent

Ce n'est pas ce que j'avais en tête, en tout cas pas en terme de déclenchement.

Si on a:

```mermaid
flowchart LR

Hote <--> Reference
Hote2 <--> Reference
```

Et qu'une variable de _Reference_ change, alors c'est bien à l'ouverture de _Hote_ et _Hote2_ qu'on va faire la vérification et alerter.

>  j'aurais remplacé l'action derrière "Visualiser" pour faire apparaître la liste des doublons et ainsi faciliter leur nettoyage

Tu me l'as montré, c'est une très bonne idée.

> Par contre, alors que j'aurais bloqué l'ajout d'une variable du questionnaire dont le nom existe déjà, j'aurais laissé faire l'import d'un questionnaire externe et sa sauvegarde.

Je veux bien qu'on en reparle :smiley:

**Comment by BulotF** [comment]
Problème de vocabulaire, mais OK sur le fond : 
3) Lorsqu'une nouvelle variable est rajoutée au questionnaire référencé, le questionnaire client (= hôte) est averti à l'ouverture suivante

**Comment by romaintailhurat** [comment]
Je fais une première recette de la fonctionnalité.

Le choix d'utiliser le bouton visualiser est intéressant (cf. plus haut) pour maîtriser l'exécution du traitement, idem pour le fait de déporter la liste des doublons dans un chemin dédié (`<host>/questionnaire/<id>/duplicate-variables`).

La fonctionnalité fonctionne déjà bien, les cas 1, 2 et 3 listés dans la description de l'issue sont couverts, je liste quand même mes remarques ici.

# UX

S'il y a une variable en doublon, le fonctionnement prévu (Visualiser > "Voir les variables en doublon") est tout de suite là. Mais si on supprime la référence qui apporte ce doublon, le message "Voir les variables en doublon" est toujours là, un _Sauvegarder_ + rafraîchir la page est nécessaire.

→ Pourrait-on avoir la même réactivité dans le deux sens ?

Plutôt que d'utiliser le dropdown de Visualiser, on pourrait:

- avoir une modale (contenant le message d'erreur et le lien)
- ou afficher le bandeau d'erreur habituel

→ Est-ce que c'est cher d'expérimenter l'un et l'autre ?

# Présentation

Les éléments graphiques (notamment la page listant les variables en erreur) pourront être améliorés. Je peux fournir des maquettes ? A arbitrer sur la priorité par rapport à la fonctionnalité avec son visuel "brut".

# Autres

`duplicated-variables` plutôt que `duplicate-variables` (ajouter un `d`)

**Comment by romaintailhurat** [comment]
# Validation

With the following questionnaires:

- H1 (Host 1), containing
  - VAR1 [_Collected_]
  - VAR_EXT_1 [_External_]
  - VAR_EXT_2 [_External_]
- R1 (Referenced questionnaire 1)
  - VAR1 [_Collected_]
  - VAR_EXT_1 [_External_]
  - VAR_CALC_1 [_Calculated_]
- R2
  - VAR1 [_Collected_]
  - VAR_CALC_1 [_Calculated_]

## Core

The core feature is __OK__.

| Use case     | Validation            | Comments |
|--------------|-----------------------|----------|
| H1 → R1      | OK :heavy_check_mark: |          |
| H1 → R2      | OK :heavy_check_mark:                    |          |
| H1 → R1 & R2 | OK :heavy_check_mark:                    |          |

## Layout

Some refinements needed, but __we can deploy without them__.

## Beyond

...

**Comment by romaintailhurat** [comment]
Last version is good enough, good job!
