### ISSUE TITLE
Questionnaire composition - Bad placement of reference when deleting structure elements

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#689]
A reference can only be placed at the sequence level. It is working when creating and moving a ref, but it does not when another element is deleted.

__How to reproduce:__

1. With the following structure:

```
-sequence1
  --question1
-ref1
-sequence2
  --question2
```

2. Delete sequence2
3. ref1 is now between two questions

_EDIT_

The expected behaviour would be to put _question2_ in _sequence1_. The structure would be then:

```
-sequence1
  --question1
  --question2
-ref1
```

**Comment by romaintailhurat** [comment]
The use case described above is working but now the app is crashing when i try to add a sequence after a ref (at least, a ref that is at the end of the questionnaire).

**Comment by nsenave** [comment]
@BulotF as it been released/deployed?
