### ISSUE TITLE
Questionnaire composition - Can't add a reference just after deleted one

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#691]
🇬🇧 

__How to reproduce__

1. click _External element_
2. choose _Reference to a questionnaire_
3. choose a questionnaire to add
4. back to the questionnaire, delete a reference (the one you just added or another one)
5. repeat 1 & 2
6. when clicking to the _Add_ button, nothing happens, and there's an error in the browser console

If we cancel by clicking the _Cancel_ button (and are back to the questionnaire), we can now retry and it will succeed.

🇫🇷 

__Comment reproduire__

1. cliquez sur _Élément externe_
2. choisissez _Référence à un questionnaire_
3. choisissez un questionnaire à ajouter
4. de retour au questionnaire, supprimez une référence (celle que vous venez d'ajouter ou une autre)
5. répétez 1 & 2
6. lorsque vous cliquez sur le bouton _Ajouter_, rien ne se passe et il y a une erreur dans la console du navigateur

Si nous annulons en cliquant sur le bouton _Annuler_ (et revenons au questionnaire), nous pouvons maintenant réessayer et cela réussira.

**Comment by laurentC35** [comment]
Done & validated
