### ISSUE TITLE
Global VTL variables to be added to completion

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#692]
At least one global variable will be added to the VTL execution engine in Lunatic: `LUNATIC_INDEX` (name will probably be changed), that will give the index of the current step in every iteration.

We would like to add this global variable (and the next ones) to the completion list of the VTL editor.

_EDIT:_ name will be `GLOBAL_ITERATION_INDEX`

**Comment by romaintailhurat** [comment]
👉 Probably a new variable source to be added [here](https://github.com/InseeFr/Pogues/blob/main/src/hoc/with-current-form-variables.js#L14).

**Comment by JulienCarmona** [comment]
On pense que la doc Bowie est suffisante pour ça, pas de besoin réel pour ce dev
