### ISSUE TITLE
[Eno V3] impossible de supprimer des variables calculées ou externes  (POGUES)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Pogues#697]
Voir lmyjrqbb : impossible de supprimer les variables calculées et externes

**Comment by romaintailhurat** [comment]
De quelle version s'agit-il ? Dans la version actuelle il y a un message d'avertissement lors de la suppression de la dernière variable mais cette suppression n'est pas interdite.

**Comment by BulotF** [comment]
Est-ce que votre environnement ne s'appuie pas sur une version de Pogues trop ancienne ? Corrigé depuis juin : 
https://github.com/InseeFr/Pogues/issues/671

**Comment by AnneHuSKa** [comment]
C'est la version sur le sandbox enov3 donc je ne sais pas trop de laquelle il s'agit ?

**Comment by nsenave** [comment]
Version `1.5.2-rc7` (la même que sur l'environnement sandbox actuellement)
