### ISSUE TITLE
suggester : mock sur les données en provenance du back

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Pogues#703]
Le front de Pogues fera 2 appels différents au back, que l'on souhaitera mocker : getNomenclatures et getNomenclature(id)

1) Pour afficher la liste des nomenclatures et en choisir une : un tableau d'objets contenant les éléments id (technique, mais on peut garder le nom métier) et label (pour affichage)

2) Pour chaque nomenclature, un fichier {id}.json (le tableau précédent permet de savoir quel fichier interroger) qui serait un objet contenant : 
- id
- name (nom du fichier généré dans le back de l'orchestrateur Lunatic)
- label
- urn : de la forme : urn:ddi:fr.insee:{idColectica}:{numeroDeVersion} 
  -  exemple : urn:ddi:fr.insee:f7cbc001-29c7-482f-98ed-9121246db5a2:2
- suggesterParameters : objet avec la structure que l'on souhaite retrouver dans Lunatic (Eno fera juste passe-plats)
- codes (pas forcément tout de suite) : contient l'ensemble de la nomenclature à des fins d'affichage dans Pogues ; tableau d'objets. Pour chaque objet : id (la valeur) ; label (le libellé en français) ; dans le cas de listes de codes hiérarchiques : parent

**Comment by romaintailhurat** [comment]
There's a Pogues BO issue for that: https://github.com/InseeFr/Pogues-Back-Office/issues/179.
