### ISSUE TITLE
A new web target for Stromae V3

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#704]
We will soon propose Stromae V3 as a target for web questionnaires.

For the visual, we will add it with a beta tag for now:

![image](https://github.com/InseeFr/Pogues/assets/1663283/0aab1083-9b59-4700-8de9-cd98fe25afcd)

@laurentC35 will give the URL that we will use first for the _sandbox_ platform.

**Comment by romaintailhurat** [comment]
```html
<li
 <a href="#">Web V3 
  <span style="color: green; border: solid green 0.5px; border-radius:10%; padding: 1px">
   <i>beta</i>
 </span>
</a>
</li>
```

**Comment by romaintailhurat** [comment]
As a supplement: could we have another "beta" link to Stromae V3 that provide a "one sequence per page" display ?

The design is the same but the text is "Web V3 par séquence".

**Comment by BulotF** [comment]
with a rename of the other new : "Web V3 par question" ?

**Comment by romaintailhurat** [comment]
Not necessary in my mind, can we try without it?

**Comment by laurentC35** [comment]
Done and deployed !
