### ISSUE TITLE
Tables - Can't import a CSV list for a table response/column

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#721]
# Description

We can't import a CSV list for a table response/column.

# How to reproduce

1. create a table
2. add a single choice response/column 
3. click on import a list
4. in the modal, upload the CSV file
5. see that you cant validate the modal

**Comment by BulotF** [comment]
The codelist name is mandatory. I just changed the label to explicit "required field" instead of "required"...

**Comment by romaintailhurat** [comment]
> Pogues [1.5.8-rc5](https://github.com/InseeFr/Pogues/releases/tag/1.5.8-rc5)

I still can't validate and i'm getting this error in the console:

![image](https://github.com/InseeFr/Pogues/assets/1663283/421ddee3-4290-4625-a7be-ac9147178b05)

**Comment by romaintailhurat** [comment]
Seems ok now 👍
