### ISSUE TITLE
Dynamic tables - UI for every control levels

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#724]
Lunatic 2 offers dynamic tables with controls. Those controls can be at three levels:

- the cell
- the row
- the table

Pogues doesn't currently have this capability. We fist need to add a conditional _Level_ field (:fr: _Niveau_) for controls over a table question.

A simple UI would be 👇 

![image](https://github.com/InseeFr/Pogues/assets/1663283/eedab967-dbdc-4920-a4d5-4bda3456912f)

**Comment by romaintailhurat** [comment]
As noted by @BulotF : we will need a way to attach the cell controls to the right cells.

Two possibilities:

1. a declarative field (appears when we choose the cell level)
2. a implicit mecanism based on the variable used in the VTL expression (__hard__)

**Comment by BulotF** [comment]
The Cell Control would be replaced by a Text format Check : https://github.com/InseeFr/Pogues/issues/746

The Row Control UI is described above.

pogues-model:
In the ControlType, add an element "Scope" with minOccurs = 0. It would be filled only for "Line Checks"

DDI:
Add 3 TypeOfComputationItem : line-warning ; line-stumblingblock ; line-informational

**Comment by romaintailhurat** [comment]
UI for the table controls seems good, but when creating a controls for a simple question, i'm getting a generation error:

`Unknown error during generation: SpEL mapping expression defined on property 'criticality', for format DDI, in class fr.insee.eno.core.model.navigation.Control, failed on object ComputationItemTypeImpl[id=lvc0qg2v-CI-1]`

**Comment by nsenave** [comment]
Eno java error: these table line controls are not implemented yet in DDI -> Lunatic

**Comment by nsenave** [comment]
Pour mémoire :

- InseeFr/Eno#986
