### ISSUE TITLE
Tables - Substitution for variables marked as not collected

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#745]
Currently we support this only by modifying the DDI, but a simple modification could support it in Pogues:

![image](https://github.com/InseeFr/Pogues/assets/1663283/618c632d-9cb9-49f8-bd3b-6b41789976f5)

Here:
- when "Collected" is unchecked, the "Substitution" field appears
- it accepts a VTL expression, but mainly we want a variable or a text here

@BulotF we need to discuss that

**Comment by BulotF** [comment]
*Contextualisation, proposition alternative et extension : *
A l'heure actuelle, dans Pogues, l'unique cas qu'il est possible de spécifier que l'on ne souhaite pas forcément collecter toutes les variables est la case non collectée, sans texte.

Ce cas a d'ailleurs des défauts de conception :
- l'action est à effectuer dans l'onglet "Variables collectées" en décochant la case "Collectée". Cette action serait plus légitime dans l'onglet "Format des réponses"
- Alors qu'aucune variable n'est collectée, cet état génère néanmoins dans le json Pogues une réponse et une variable collectée inutiles. 

*Les besoins auxquels on souhaite répondre :*
- spécifier un texte comme alternative de la variable collectée (texte en VTL : pour gérer le texte comme dur aussi bien que la valeur d'une variable externe qui sert à initialiser le tableau dynamique)
- appuyer sur un filtre le choix de collecter la variable ou non. Par exemple, dans un tableau dynamique personnalisé, pour les colonnes personnalisées, on a une variable collectée sur lignes ajoutées  ; dans un tableau dynamique avec Suggester multiple, une colonne de la nomenclature peut permettre d'indiquer si l'on souhaite collecter une des variables du tableau (ex : montant de la sous-traitance)

*Proposition d'UX :*
Déplacement de la notion de "Collectée" de l'onglet "Variables collectées" à l'onglet "Format des réponses" et enrichissement de l'interface pour les cas autres que "Collectée" :
- évolution de l'onglet Variables collectées :
  - suppression de la case à cocher "Collectée"
  - restriction de la liste des variables générées à celles qui sont effectivement collectées

- évolution de l'onglet "Format des réponses" :
  - Cas des tableaux dynamiques :
    - Ajout d'un bouton radio "Collecté ?" avec 3 modalités : "Toujours" (valeur par défaut) ; "Jamais" ; "Sous condition"
    - Sélectionner "Toujours" ne fait rien apparaître de plus
    - Sélectionner "Jamais" fait apparaître une zone de libellé "Libellé de substitution"
    - Sélectionner "Sous condition" fait apparaître une zone de formule "Condition de collecte" et une zone de libellé "Libellé de substitution"

  - Cas des tableaux normaux :
    - Ajout d'une case à cocher "Tout collecter" cochée par défaut.
    - Décocher cette case fait apparaître pour chaque modalité de la liste de codes de l'axe d'information principal :
      - le libellé de la modalité
      - le bouton radio "Collecté ?" décrit dans le cas des tableaux dynamiques (avec les comportements associés)

*Evolution de Pogues-model :*
- Ajouter un AttributeLabel de type xs:string (comme les autres Label) avec un minOccurs = 0
- Ajouter une enumeration à FlowControlTypeEnum, qui ne peut actuellement valoir que CLARIFICATION : COLLECTCELL

*Evolution du DDI*
- Pour le libellé sur case non collectée, l'utilisation de d:CellLabel est déjà documenté et utilisé dans la transformation ddi2xforms
- Ce d:CellLabel permet aussi de rajouter un libellé sur une case collectée. Néanmoins, le système de filtre interne à un d:QuestionGrid, utilisé dans le cadre de la question de clarification à une réponse (d:GridResponseDomainInMixed / d:ResponseAttachmentLocation / d:DomainSpecificValue / @attachmentDomain de la réponse de précision a la même valeur que d:GridResponseDomainInMixed / @attachmentBase pour la réponse qui peut être "Autre"), restreint les possibilités de filtre à une liste de valeurs d'une réponse. Et là, on souhaiterait faire porter le filtre sur une variable calculée ou externe, voire une formule... Détails : https://github.com/InseeFr/Bowie/issues/87

**Comment by BulotF** [comment]
L'UI est plus compliquée à rendre claire que prévu.
Dans les sujets : quel est le format de réponse des colonnes dont aucune case n'est collectée ? (on peut avoir le cas au moins pour des tableaux dynamiques)
Sachant que lors de l'import des questionnaires présents en base, cette information est calculée à partir du formats de la variable dans la première case de la colonne...

A l'enregistrement en base, toutes les variables sont créées avec le format de la colonne et associées à des réponses, mais une information complémentaire permet d'indiquer qu'elles sont inutiles...
Est-ce que c'est le bon moment de refondre la gestion case à case des tableaux dans Pogues ?

**Comment by BulotF** [comment]
Au final, évolution de l'UI uniquement sur l'onglet "Variables collectées" avec clarification du contenu.
L'évolution principale concerne la case à cocher "Collecté"
- elle est remplacée par un bouton radio qui prend 3 valeurs : "Oui" (sélectionné par défaut), "Non", "Sous condition"
- elle est toujours affiché uniquement pour les tableaux et les QCM
- lorsqu'elle est affichée, elle est affichée en premier
- ses évolutions ont des effets sur l'affichage de la suite

- Modalité "Oui" ou non affichée (réponses simples)
  - Comme auparavant : Nom et libellé de la variable ; Caractéristiques du format
  - évolution : "Liste de codes" n'apparaît que lorsqu'elle a du sens
 
- Modalité "Non" : 
  - Apparition d'un champ nouveau : "Libellé alternatif"
  - disparition des champs : "Nom", "libellé" et champs en lien avec le format
  - le lien dans la liste des variables comporte les coordonnées puis [nom collecté] au lieu du nom inutile de la variable
 
- Modalité "Sous condition" : 
  - Champs nouveaux : 
    - "Condition d'affichage"
    - "Libellé alternatif"
  - puis tous les champs que l'on a avec la réponse "Oui"
  
Au niveau des données : 
- si "Non" : "AlternativeLabel" rajouté dans l'Attribute (informations de non-collecte de la case)
- si "Sous condition" : "Condition" et "AlternativeLabel" rajoutés dans le "MappingSource" qui fait le lien entre la case et la réponse

**Comment by romaintailhurat** [comment]
@BulotF On fait le point à ton retour sur cette fonctionnalité

**Comment by romaintailhurat** [comment]
Validation des devs une fois que la partie Eno est faite pour un test de bout en bout.

**Comment by romaintailhurat** [comment]
Deuxième élément: une proposition de retouche de la présentation du bouton pour les cases non-collectées, avec le texte fixe "Case non collectée" en italique, et un début de formule dans la même police que le nom de la variable dans le cas d'une collectée.

![image](https://github.com/InseeFr/Pogues/assets/1663283/b080f620-0a24-49ef-b56c-b967ddffcc50)
