### ISSUE TITLE
Second instruction doesn't have default modes

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#753]
When creating a new instruction attached to a question, the modes for this declaration are the modes of the questionnaires:

![image](https://github.com/InseeFr/Pogues/assets/1663283/d42dae9f-673f-4f9a-8e53-92ff1075c068)

But starting with the second instruction, no mode is checked:

![image](https://github.com/InseeFr/Pogues/assets/1663283/7909decf-9421-484f-86bf-f9953ebe2813)

This could leads to non wanted behaviors.

Expected behavior is to have each new declaration with the modes declared at the questionnaire level.

**Comment by QRuhier** [comment]
@romaintailhurat Question for the future : is there a reason why the declarations default modes are the questionnaire modes and not the modes of the current object (question, sequence...)

**Comment by romaintailhurat** [comment]
No good reason i think, and indeed it would make more sense to inherit from the Sequence / Question and not from the Questionnaire.
