### ISSUE TITLE
Add [deprecated] in the label of visu for Web V2 (like beta tag but in red)

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Pogues#758]
![image](https://github.com/InseeFr/Pogues/assets/38245508/fcbf99cf-1dcd-44c4-9ced-161f34ed5aac)

**Comment by romaintailhurat** [comment]
In french, "obsolète"?

![image](https://github.com/InseeFr/Pogues/assets/1663283/4c558ed4-6fb0-41eb-a9b4-e77dbc727180)

Problem is that we can have both a beta and a deprecated web target, can we?

**Comment by laurentC35** [comment]
Delete V2 visu
