### ISSUE TITLE
Instruction management refactor

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#761]
A new set of constraints for declaration / instruction in Pogues, see [this table](https://hackmd.io/E7dUZ-sGRWu5-yMHDXxM-A?view#D%C3%A9clarations-produites-par-latelier---tentative-de-mise-%C3%A0-plat) (in 🇫🇷 ).

I propose that when a choice is not compatible with a specific mode, we don't display the mode in Pogues.

For example, an interviewer instruction can't be chosen for CAWI, so the mode is not available in the checkboxes 👇 

![image](https://github.com/InseeFr/Pogues/assets/1663283/dddd510a-c13a-4aaa-a3ca-ff894c04c654)

**Comment by JulienCarmona** [comment]
Sera fait dans cette story 
- https://github.com/InseeFr/Concevoir-Workplace/issues/87
