### ISSUE TITLE
Tables - Allow VTL for min/max for dynamic tables

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#762]
Lunatic allows min/max to be produced by VTL code, but Pogues forbid to enter anything else than number.

The min and max fields below should accept a VTL expression (for example a variable name):

![image](https://github.com/InseeFr/Pogues/assets/1663283/b26854a9-d767-42f0-b0f2-37edacbf3b57)

**Comment by AnneHuSKa** [comment]
**Rappel du besoin à couvrir** : affichage d'un tableau dynamique dont la première colonne est préremplie avec un nb de lignes déterminé dans le fichier échantillon (et donc différent d'une unité à l'autre).

Exemple cible
![image](https://github.com/user-attachments/assets/f1fb5dd9-4e55-4478-8867-cb3fb78753bf)

Actuellement on ne sait faire que cela : 
![image](https://github.com/user-attachments/assets/d234c0e3-055f-4703-9e3a-3ec38c1e2a84)
(produit 2 et produit 3 sont masqués si on met 1 par défaut).

**Comment by QRuhier** [comment]
needs :
- update pogues-model
- find ddi modelisation

**Comment by romaintailhurat** [comment]
> not sure that we can directly give VTL expression as minimumRequired and maximumAllowed values

Indeed we can't: https://ddialliance.github.io/ddimodel-web/DDI-L-3.3/composite-types/RosterType/

We have three possibilities:

1. we use a UserKeyValuePair at the QuestionGrid level (it's sad)
2. we use `ConditionForContinuation` on the Roster (it's a hack)
3. we ask for an evolution of the standard (it's a far shot)

**Comment by JulienCarmona** [comment]
Need to prioritize this ticket @AnneHuSKa @lailabent

**Comment by JulienCarmona** [comment]
Pour le visuel, on voudrait, lorsque l'utilisateur sélectionne `Liste` pour le champ **"Format de l'axe principal*"**, avoir une nouvelle ligne juste en dessous avec le libellé : "Calcul du nombre de lignes". 
et deux options avec une seule sélection possible (comme pour l'axe principal) : `Min/Max` et `Formule`
![image](https://github.com/user-attachments/assets/21e654b7-6aa2-48e8-b63f-2b4d84319a68)

**Comment by QRuhier** [comment]
# Things to check

As the modelization changed, we need to check that still can read the 'old' questionnaires.

- create a new questionnaire, with this content (just update the id) : .......
- [ ] open the questionnaire, check that the questionnaire is well loaded
- [ ] open the 4 existing questions, check that what you have still corresponds to what is described in the question label 
- [ ] add a new question : table with list, with a min/max for number of lines
  - [ ] also check that min & max are still mandatory (cannot validate question if fields are empty) 
- [ ] add a new question : table with list, with a formula for number of lines
  - [ ] also check that formula is mandatory (cannot validate question if field is empty)
- [ ] save questionnaire, reload. Open the 2 questions you've added and check that it still corresponds to what you've set
