### ISSUE TITLE
[Suggesters] Nouvelles listes

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Pogues#771]
Voici 8 listes à intégrer : ce sont des régions frontalières pour Belgique, Suisse, Allemagne, Espagne, Italie, Pays-Bas et Royaume Uni et une liste pour les types de voie.  

Noms des listes : 
- régions frontalières Belgique
- régions frontalières Suisse
- régions frontalières Allemagne
- régions frontalières Espagne
- régions frontalières Italie
- régions frontalières Pays-Bas
- régions frontalières Royaume Uni
- Types de voie

Pour les intégrer, on prend les paramètres de "communes".

[L_REGFRONT_IT-1-0-0.json](https://github.com/user-attachments/files/15740506/L_REGFRONT_IT-1-0-0.json)
[L_REGFRONT_NL-1-0-0.json](https://github.com/user-attachments/files/15740507/L_REGFRONT_NL-1-0-0.json)
[L_REGFRONT_UK-1-0-0.json](https://github.com/user-attachments/files/15740508/L_REGFRONT_UK-1-0-0.json)
[L_TYPEVOIE-1-0-0.json](https://github.com/user-attachments/files/15740509/L_TYPEVOIE-1-0-0.json)
[L_REGFRONT_BE-1-0-0.json](https://github.com/user-attachments/files/15740510/L_REGFRONT_BE-1-0-0.json)
[L_REGFRONT_CH-1-0-0.json](https://github.com/user-attachments/files/15740511/L_REGFRONT_CH-1-0-0.json)
[L_REGFRONT_DE-1-0-0.json](https://github.com/user-attachments/files/15740512/L_REGFRONT_DE-1-0-0.json)
[L_REGFRONT_ES-1-0-0.json](https://github.com/user-attachments/files/15740513/L_REGFRONT_ES-1-0-0.json)

**Comment by QRuhier** [comment]
@AnneHuSKa In same time, do you want to sort the list by label ? It is currently not sorted

**Comment by QRuhier** [comment]
Also add these nomenclatures in questionnaire-api : 
- [x] qf
- [x] prod

**Comment by QRuhier** [comment]
Also add another nomenclature, replacing L_COMMUNEPASSEE-1-2-0 : L_COMMUNES-2024

**Comment by AnneHuSKa** [comment]
@QRuhier : je regarde demain
