### ISSUE TITLE
Criticity level for controls, drop Error

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#780]
The current criticality options for controls are:

- _Information_
- _Warning_
- _Error_

In the future, _Error_ will be interpreted as a blocking control, but this feature is not yet implemented.

So for now, we will limit the options to:

- _Information_
- _Warning_

**Comment by AnneHuSKa** [comment]
Ces controles arriveront peut-être plus vite que prévu donc issue fermée
