### ISSUE TITLE
Handle correctly filter on the Roundabout loop sequences

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#791]
Consider this questionnaire:

![image](https://github.com/user-attachments/assets/03a82406-ee33-46be-a5be-727fba27308a)

When trying to generate, i get a nasty Pogues2DDI error:

```
Eno generation error: An error was occured during the POGUES_XML_GOTO_2_ITE transformation. 
A sequence of more than one item is not allowed as the first argument of fn:number() 
(@position="16", @position="24", @position="16", ...) : 
Error in :/xslt/pre-processing/pogues-xml/goto-2-if-then-else.xsl ; SystemID: ; Line#: 478; Column#: 7
```

Indeed, there is a problem because the Roundabout component cannot be included in the filter starting on S2.

Could the problem be solved by allowing that inclusion?

**Comment by AnneHuSKa** [comment]
Dans ce cas, le filtre doit être sur le SAUF du rond point non ? @BulotF @nsenave ?

**Comment by BulotF** [comment]
Oui. Il y a là une erreur de logique de mon point de vue : 
On n'est pas censé pouvoir filtrer l'intégralité du contenu d'une boucle (ici, définie dans un rond-point) : c'est bien au niveau du Sauf que ça doit être géré.
Il faut indiquer à ton individu qu'il n'a pas à répondre à la séquence, plutôt que lui dire qu'il doit répondre à... rien !
Par contre, si tu avais eu S2 et S3 au sein de ton rond-point, tu pouvais peut-être filtrer S2 uniquement (même si ça fait bizarre de filtrer le premier élément d'une boucle...)
