### ISSUE TITLE
Ajouter un controle sur les occurrences du rond point 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Pogues#792]
Besoin : pouvoir afficher un message d'erreur en cas de par exemple non remplissage ou incohérence d'une occurrence d'un rond point

- https://github.com/InseeFr/Lunatic/issues/1069
- https://github.com/InseeFr/Lunatic/pull/1070

**Comment by AnneHuSKa** [comment]
Source @BulotF :
DDI :
Le rond-point est une séquence à laquelle on peut attacher les contrôles globaux.
Il contient une ou plusieurs boucles qui contiennent chacune une séquence de type loopContent ou filteredloopContent à laquelle on peut attacher les contrôles d'occurrence.

Pogues UI :
Le rond-point a déjà 2 onglets : Boucle et déclarations.
Rajouter un onglet Contrôle basé sur l'existant.
Comme pour les tableaux dynamiques, proposer de préciser le niveau avec 2 modalités : global / occurrence

Pogues-model :

    le RoundaboutType est une extension du ComponentType. A ce titre, il est déjà autorisé à avoir des Control.
    depuis les contrôles de tableau dynamique, ControlType dispose d'un scope de type xs:string

Aucune évolution n'est nécessaire pour Pogues-model

**Comment by JulienCarmona** [comment]
Reste DDI -> Lunatic
