### ISSUE TITLE
Variable collectée sur tableau standard à 2 dimensions avec réponses de type booléen : génération en boucle

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Pogues#793]
Pogues semble refuse de valider la création d'une variable non collectée dans une liste de codes : il demande de générer les variables.
Quand on génère, Pogues redonne un nom à la variable
Si on remet en non collecté (avec "") , Pogues redemande de générer les variables, ça tourne en boucle
___________________
Idep en prod : lyrcwaydah
Idep en QF : lz9p8q74
_________________
Comment avoir l'erreur : 
- aller dans la variable
- tenter sur une des variables collectées de faire "non collecté"
- valider la variable
- valider la page => impossible car demande de regénérer les variables

**Comment by BulotF** [comment]
Le problème provenait du rajout du libellé dans une case non collectée de tableau à 2 dimensions.

On comparait le contenu de la variable dans son état avant validation avec ce que donnait la génération.
A la génération, on lui attribuait un libellé vide, au lieu de ne pas lui attribuer de libellé.

1 ligne supprimée : bon pour recette

**Comment by AnneHuSKa** [comment]
@BulotF : je n'ai pas l'impression que ce soit déployé ?

**Comment by JulienCarmona** [comment]
C'est bon ça marche sur [QF](https://conception-questionnaires.recette.insee.fr/)
