### ISSUE TITLE
Mise à jour des listes de produits de l'EAP

### ISSUE THREAD

**Issue by lailabent** [InseeFr/Pogues#801]
en cours de rédaction (des précisions sont en attente coté concepteurs + json à déposer)

Les concepteurs de l'enquête nous ont fourni une mise à jour des liste de produits à intégrer à Pogues pour les suggester.

Il faut remplacer 

- L_PRODEAP_DECHETS_2022 (liste actuelle) par L_PRODEAP_DECHETS_2024 (nom pour la nouvelle liste) "EAP - Produits - déchets" issue du fichier prodeap_dechets.json
- L_PRODEAP_EAU_2022 (liste actuelle) par L_PRODEAP_EAU_2022 (nom pour la nouvelle liste) "EAP - Produits - eau" issue du fichier prodeap_eau.json
- L_PRODEAP_INSTAL_REPAR_2022 (liste actuelle)  par L_PRODEAP_INSTAL_REPAR_2024 (nom pour la nouvelle liste) "EAP - Produits - installation - réparation" issue du fichier prodeap_instal.json
- L_PRODEAP_VPI_2022 (liste actuelle) par L_PRODEAP_VPI_2024 (nom pour la nouvelle liste) "EAP - Produits - vente de produits industriels" issue du fichier prodeap_VPI.json
- L_PRODEAP_VPNI_2022 (liste actuelle) par L_PRODEAP_VPNI_2024 (nom pour la nouvelle liste) "EAP - Produits - vente de produits non industriels" issue du fichier prodeap_VPNI.json

Il faut supprimer

- L_PRODEAP_ENERGIE_2022 (liste actuelle)

et créer 3 nouvelles listes (qui remplacent celle sur l'énergie)

- L_PRODEAP_VAPEUR_2024 (nom pour la nouvelle liste) "EAP - Produits - vapeur" issue du fichier prodeap_vapeur.json
- L_PRODEAP_GAZ_2024 (nom pour la nouvelle liste) "EAP - Produits - gaz" issue du fichier prodeap_gaz.json
- L_PRODEAP_ELEC_2024 (nom pour la nouvelle liste) "EAP - Produits - électricité" issue du fichier prodeap_electricite.json

Les fichiers json mentionnés sont stockés dans le dépôt Gitlab correspondant 
https://gitlab.insee.fr/enquetes-menages/integration-metallica/-/tree/master/_Nomenclatures/EAP

**Comment by QRuhier** [comment]
Also add the new nomenclatures in questionnaire-api : 
- [x] qf
- [x] prod

**Comment by lailabent** [comment]
Une liste supplémentaire à créer

L_PRODEAP_VPIZ_2024 (nom pour la nouvelle liste) "EAP - Produits - commerce" issue du fichier PRODEAP_VPIZ_2024.json
