### ISSUE TITLE
Questionnaire Visu V1 - Bad Gateway

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Pogues#858]
### Sample 
https://conception-questionnaires.insee.fr/questionnaire/lycyzzbv

### Bug 
502 bad gateway ou time out

### Explication
On pense qu'on a une limitation au niveau des ressources des serveurs, car le questionnaire est très volumineux.

### Solution
Tester en augmentant les ressources ?

**Comment by JulienCarmona** [comment]
### Testé en QF ❌ 
message d'erreur qui ressemble a un time out mais qui n'est pas le time-out 504
![image](https://github.com/user-attachments/assets/a57f26ae-1b18-463a-bf59-d06975c90c25)

### Causes possibles
- Base donnée eXist (base de données document XML, utilisé par Coltrane) H.S
- coquille dans les variables d'environnement (on le voit dans le message d'erreur, bowie-dv-xxx au lieu de bowie-qf-xxx)

**Comment by laurentC35** [comment]
La solution en augmentant les ressources mémoire pour orbeon (pas eXist) fonctionne.

Nous pouvons clôturer cette issue.
