### ISSUE TITLE
Documenter Roundabout component - DDI model

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Pogues#864]
Documenter dev fait ici 
- #649 

- [ ] Faire une issue Pogues-Model + Eno
- [ ] Trouver emplacement de documentation
- [ ] Documenter

**Comment by nsenave** [comment]
@JulienCarmona j'ai fait ça, ça a l'air de correspondre à ce que tu veux : 

- https://github.com/InseeFr/ddi-questionnaire-modeling/pull/22/files

**Comment by JulienCarmona** [comment]
Yes, c'est parfait, j'ai review d'ailleurs, RAS

Je close donc ce ticket car doublon du travail fait dans le ticket de dev de base
