### ISSUE TITLE
Bug sur les boucles : persistance des paramètres min/max dans le Pogues model  lorsqu'on change de type de boucle dans Pogues

### ISSUE THREAD

**Issue by lailabent** [InseeFr/Pogues#867]
## Describe the bug

Dans Pogues, lorsque l'utilisateur crée une boucle basée sur des paramètres min/max (boucle paginée) une première fois puis change d'avis et la modifie avec des paramètres pour baser la boucle sur une autre boucle précédemment créée (boucle liée), le json Pogues model garde en mémoire les 1ers paramètres min/max bien que dans l'IHM la boucle soit décrit à l'écran comme boucle liée.
 De plus à la visualisation, la boucle se comporte (conformèment au Pogues model qui a gardé en mémoire les min/max à tort) comme une boucle paginée et pas comme une boucle liée.

## To Reproduce

Utiliser le Pogues model suivant pour créer un questionnaire
[response_1729068260378.json](https://github.com/user-attachments/files/17392228/response_1729068260378.json)

La BOUCLECOLLEGUES est décrite avec des paramètres min/max.
La modifier à l'IHM pour en faire une boucle liée à la boucle BOUCLEPRENOM

Si on visualise le questionnaire créé on voit qu'on est toujours sur une boucle paginée et si on récupère le nouveau Pogues Model, la boucle est toujours définie avec des min/max et pas comme liée à BOUCLEPRENOM.

## Expected behavior

Après modification des paramètres de la boucle BOUCLECOLLEGUES à l'IHM Pogues pour la spécifier comme basée sur la boucle BOUCLEPRENOM, les premiers paramètres min/max devraient avoir disparu du Pogues Model et être remplacés par une IterableReference à la boucle BOUCLEPRENOM

## Version where the bug appeared

Pogues 1.7.2

**Comment by JulienCarmona** [comment]
Validate in QF: ✔
