### ISSUE TITLE
Can't Generate Collected Var with Table and QCU in measured data

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Pogues#868]
## Describe the bug
Ne peut pas créer un tableau (**dynamique ou fix**) avec une colonne à base de modalités à choix unique quand cette dernière n'est pas en première position.

## To Reproduce

1. Dans un tableau dynamique, créer une info mesurée avec réponse à choix unique et une lise de modalités.
2. Générer des var collectées.
3. Valider la question
4. Bug : Modale indiquant de générer les variables collectées s'affiche à tort

## Expected behavior

On devrait pouvoir créer la question.

## Other Info
Fonctionne bien si le QCU est la première colonne du tableau

## Screenshots

![image](https://github.com/user-attachments/assets/004aff08-b926-46a4-ac15-0705c56ebc11)

![image](https://github.com/user-attachments/assets/c5501e14-fc0e-459a-93ea-7540602e9cba)

## Version where the bug appeared

[Pogues 1.7.2](https://github.com/InseeFr/Pogues/releases/tag/1.7.2)

**Comment by JulienCarmona** [comment]
À déterminer avec l'Info si c'est normale.

**Comment by AnneHuSKa** [comment]
mémo : c'est vrai que ca n'a pas du être un cas prévu car c'est assez peu naturel comme questionnement (les tableaux dynamiques sont plutôt prévus pour de la collecte de données, pas de QCU/QCM) et si ca ne marche pas dans Pogues, ca n'a pas été utilisé dans la filière Orbeon.
C'est un contournement qu'on imagine pour une demande EEC mais plutôt se pencher sur la vraie solution qu'on viserait pour EEC

**Comment by JulienCarmona** [comment]
Ok donc besoin Low dans le sens que cela n'a jamais marché

**Comment by JulienCarmona** [comment]
## ⚠️ **Update** ⚠️ 
Ça ne fonctionne pas non plus pour les tableaux fixes donc on a bien une regression !

À prioriser

**Comment by BulotF** [comment]
Et de mémoire, Ofats a des QCU dans les 2 premières colonnes de ses tableaux dynamiques (ils demandent des informations par produit * pays), donc le besoin était déjà couvert.

**Comment by AnneHuSKa** [comment]
C'est uniquement dans les tableaux dynamiques ?
Si c'est dans les tableaux fixes, ca semble proche de https://github.com/InseeFr/Pogues/issues/793 ou bien je n'ai pas trop compris ?

Pour OFATS : leurs deux premières colonnes sont des listes déroulantes je crois, modifiables par l'enquêté

**Comment by JulienCarmona** [comment]
Le problème est présent pour les tableaux dynamiques **ET** fixes.

⚠ Marche si le QCU est la première colonne. Ca peut peut être aider à trouver la cause ?

**Comment by QRuhier** [comment]
>Fonctionne bien si le QCU est la première colonne du tableau

A priori ça n'a juste jamais l'air de fonctionner s'il y a une QCU, quelle que soit la colonne

**Comment by QRuhier** [comment]
@JulienCarmona Il semblerait plutôt que pour la QCU ça fonctionne uniquement si on importe une liste ou qu'on en réutilise une déjà existante. Il est donc impossible (peu importe la colonne) de créer une QCU avec une nouvelle liste

**Comment by lailabent** [comment]
Recette faite en QF1 1.7.4-RC.0
Done, on peut créer des QCU dans des tableaux quelle que soit la position de la colonne (tableaux de taille fixe ou dynamique avec et sans formule)
Lors de la recette on a mis en évidence un autre bug démoniaque [persistance de la dernière liste de codes créée dans les modalités qui s'appliquent automatiquement aux nouvelles QCU et on peut changer sans fin la liste, tout reste lié à moins de cliquer sur "dupliquer la liste de codes", cf draft  https://github.com/orgs/InseeFr/projects/18/views/1?pane=issue&itemId=88981345 ]
