### ISSUE TITLE
Maj Nomenclature

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Pogues#871]
Mettre à jour la liste des nomenclatures embarqués dans les env de Pogues en prenant cette liste
https://gitlab.insee.fr/enquetes-menages/integration-metallica/-/tree/master/_Nomenclatures/_LISTES_EXHAUSTIF?ref_type=heads

**Comment by QRuhier** [comment]
to do : 

- ajouter les listes dans Pogues
- créer les nomenclatures côté api-questionnaire dans les environnements suivants :
  - DV(/QF)
  - prod
  - demo

**Comment by QRuhier** [comment]
Côté Pogues : juste besoin d'actualiser la version de L_LANGUES

**Comment by JulienCarmona** [comment]
Rest à faire : 
- Mettre à jour démo avec la PROD (au moins les nomenclatures de la liste exhaustive)

**Comment by JulienCarmona** [comment]
done
