### ISSUE TITLE
Environnement demo (PROD des SSM) Impossible de choisir une unité pour une réponse simple de type nombre

### ISSUE THREAD

**Issue by lailabent** [InseeFr/Pogues#879]
## Describe the bug

Dans l'environnement de prod des SSM (demo), on ne peut pas choisir une unité lorsqu'on crée une question avec une réponse simple de type nombre. Le menu déroulant qui permet de sélectionner les unités ne s'ouvre pas.

![Image](https://github.com/user-attachments/assets/ef7081b4-f5b7-45a8-88e1-10690829a1c0)

## To Reproduce

Créer un questionnaire dans l'environnement demo 
Créer une séquence et une question (cf copie d'écran)
Essayer de choisir une unité dans le menu déroulant

## Expected behavior

Le menu déroulant des unités s'ouvre pour permettre de sélectionner l'unité

## Version where the bug appeared

Pogues 1.7.3 (demo)

**Comment by QRuhier** [comment]
@laurentC35 même sujet que le fait de ne pas pouvoir sélectionner de série/opération à la création de questionnaire : tout est fourni par l'api Pogues, qui récupère elle-même les informations de Rmés => problème de branchement Rmés en démo

**Comment by laurentC35** [comment]
Yep, en effet c'est un problème plus large que ça.

Ça pose la question de l'ouverture de Bowie en DMZ, avec l'authentification et tout ce qui va avec.

On peut proposer une solution court termiste, mais ce n'est pas forcément souhaitable.

**Comment by JulienCarmona** [comment]
1. Si utilisateur bloqué et ne peut pas attendre 
-> solution court termiste
2. Si utilisateur peu attendre
-> Dynamic Unit serait une bonne solution car l'utilisateur à juste besoin de mettre en dur l'unité qu'il souhaite. Ca évite de dev une solution temporaire

Et ensuite oui on prendra le temps de régler ces pb avec Bowie en DMZ

Pour le fait de mock les séries en démo, Ce serait intéressant de juste statuer de votre côté sur pourquoi ça ne marche plus et estimer rapidement combien ça coute de remettre en place le mock.
Etude à faire ici https://github.com/orgs/InseeFr/projects/18/views/1?pane=issue&itemId=88827734

**Comment by JulienCarmona** [comment]
Vu avec le métier, pas urgent donc on va attendre que [Dynamic Unit on Input Number](https://github.com/InseeFr/Concevoir-Workplace/issues/46) soit deployed

Je close en won't do
