### ISSUE TITLE
Multiples QCU in Dyn Tab - WTF - List doing evil 😈😈😈

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Pogues#880]
## Demo
https://github.com/user-attachments/assets/fb39c607-8d5d-4b69-97a9-230ce793e0cf

## Bug
1. Create Q of type Dyn Tab
2. add a QCU in Information mesurée with new list - LIST1 = code11 and validate
3. add another QCU with new list - LIST2 = code21,code22 and validate
4. add a laste QCU with new list - LIST3 = code31,code32,code33 and validate
5. Generate collected var and save Q
6. See details of Q and look at Format des reponses
7. display LIST1 then LIST2 then LIST1 then LIST3 then LIST2
8. BUG - sometime you can see that the content of LIST2 is the content of LIST3 and vise versa
9. Visual is not robust

## Solution
We should have a clear difference between LIST when we switch of display

## Version
- PROD : [1.7.3](https://github.com/InseeFr/Pogues/releases/tag/1.7.3) 
- QF : [1.7.4-rc.0](https://github.com/InseeFr/Pogues/releases/tag/1.7.4-rc.0)

**Comment by lailabent** [comment]
US migrée dans tuleap https://tuleap.insee.fr/plugins/tracker/?tracker=832&aid=9923
