### ISSUE TITLE
Visu KO - IndexOutOfBoundsException: Index 8 out of bounds for length 8

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Pogues#883]
## Bug de visu
![Image](https://github.com/user-attachments/assets/b462a097-6a32-4a18-a114-685c769c611a)

Env : **Demo**
Questionnnaire : **ly4nbfn0** (EHIS 2025 - questionnaire test EST - Module 2 : Recours aux soins)

## Note
La génération DDI fonctionne bien.
Je note cependant qu'on a dedans des var avec un seul `$`
![Image](https://github.com/user-attachments/assets/9078dcd6-5b80-4ac9-90ee-438d1732f1c6)
Ici `$HS2REF= "1"`
Pourtant, on a bien le filtre dans Pogues avec les deux `$
![Image](https://github.com/user-attachments/assets/5e79a027-012b-4182-bea9-9df0f2cb99a9)

Pb de génération Eno ?

J'ai essayé de supprimer les filtres qui posent pb mais ca change rien

## Version
Pogues - [1.7.3](https://github.com/InseeFr/Pogues/releases/tag/1.7.3)

# Solution 
Côté génération, on peut implémenter une amélioration à faible coût pour améliorer la gestion de l'erreur de ce cas là (pas souhaitable de tomber sur une IndexOutOfBoundsException) : ici ça donnerait quelque chose comme :
```
Code list CodeList[id=lxyri80e, name=SOINS] has 9 codes, and is used in multiple choice question SimpleMultipleChoiceQuestion[id=ly4kdxba, name=UNX0BIS] that has 8 responses.
```

**Comment by AnneHuSKa** [comment]
@JulienCarmona Variable UNX0BIS : elle a 8 variables collectées mais 9 lignes dans sa liste de réponses.
Astuce : tenter la génération sous séquence par sous-séquence, puis question par question pour identifier le souci


La présence de $ est lié au fait que la variable HS2REF n'est que référencée dans ce questionnaire, mais pas créée.

**Comment by nsenave** [comment]
Côté génération, on peut implémenter une amélioration à faible coût pour améliorer la gestion de l'erreur de ce cas là (pas souhaitable de tomber sur une `IndexOutOfBoundsException`) : ici ça donnerait : 

```
Code list CodeList[id=lxyri80e, name=SOINS] has 9 codes, and is used in multiple choice question SimpleMultipleChoiceQuestion[id=ly4kdxba, name=UNX0BIS] that has 8 responses.
```

**Comment by AnneHuSKa** [comment]
@JulienCarmona @lailabent Je déplace en sprint 4 car pas prio mais ca serait top @nsenave

**Comment by JulienCarmona** [comment]
@nsenave si tu peux estimer le coup de cette évolution ? Et le passer en triage. Comme ça on prévoit ça pour le prochain sprint

**Comment by nsenave** [comment]
Pour mémoire je remets le message que je vous avez envoyé : 

> L'utilisateur a ajouté un code dans une liste de code, et n'a pas re-généré les variables collectées sur les questions à choix multiple qui utilisent cette liste de code.

> 1. Pogues UI gère pas ce cas là on dirait
> 2. Pogues back fait pas de contrôle à ce niveau là
> 3. Eno Pogues -> DDI plante pas mais le DDI résultant a des problèmes
> 4. Eno DDI -> Lunatic s'en rend compte un peu par hasard quand il essaye de mapper les libellés de la liste de code sur les "responses" de l'objet question à choix multiples ("CHECKBOX\_GROUP") : la liste de code a un code en trop => `IndexOutOfBoundsException`

Les actions à mener pour améliorer l'expérience utilisateur (tout ou partie ça sera à vous de juger) : 

- [ ] Correction dans Pogues UI pour que si une liste de code change, l'utilisateur soit invité à re-générer les variables des questions qui en dépendent (coût XL je dirais, sans doute tricky à faire)
- [ ] Ajouter un contrôle pour ce cas là côté back (coût S, assez simple à faire)
- [ ] Pour la partie Eno xslt Pogues -> DDI je propose de laisser tel quel de loin ça me paraît compliqué à gérer
- [x] Pour la partie Eno java DDI -> Lunatic cf. ci-dessous : 

@JulienCarmona J'avais déjà tout sous la main quand j'ai debug dans Eno java (j'ai mis la PR direct dans le backlog d'équipe) : 

- InseeFr/Eno#1167

**Comment by lailabent** [comment]
Migrée vers luleap
https://tuleap.insee.fr/plugins/tracker/?aid=9920
